### ISSUE TITLE
Start page – SRS information

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#12]
### Describe the solution you'd like

**As a** new user
**I need** to understand how to access the NPD data through ONS
**in order to** apply for the correct accreditations prior to an application

### Scenarios
**Given** I'm an anonymous user
**When** I go to the service start page
**Then** I see a description of the ONS SRS and Accredited Researcher programme
**and** links to further (external) information

**Comment by krios82** [comment]
https://www.ons.gov.uk/aboutus/whatwedo/paidservices/virtualmicrodatalaboratoryvml

**Comment by spikeheap** [comment]
Blocked: are we keeping this page of just using the guidance CRM?
