### ISSUE TITLE
Admin page – breadcrumbs in Rails admin for edit category page

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#122]
### Allows an admin user on to see which strand of the category tree they are on when editing a category 

**As a** Find and Explore admin user
**I want** to understand where in the category tree I am when I am editing a category
**in order to** avoid editing the wrong area

### Scenarios

1. Breadcrumbs for category page
**Given** that I am on the List of Categories admin page
**When** I click to view the 'KS5 pupil retention' category
**Then** Then I am taken to the 'KS5 pupil category' admin page
And i see the 'breadcrumb' list of category tree pages that lead me to the 'KS5 pupil retention' category page

(Breadcrumbs seen should be: 'Home, Attainment, School and exam registration, KS5 pupil retention')

**Comment by RICHARDMACHEN1** [comment]
@benmemmott Looks fine. The first sentence doesn't quite make sense 'Allows....'
