### ISSUE TITLE
Admin page – breadcrumbs in Rails admin for edit concept pages

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#124]
### Allows an admin user to see which strand of the category tree they are on when editing a concept

**As a** Find and Explore admin user
**I want** to understand where in the category tree I am when I am editing a concept 
**in order to** avoid editing the wrong area

### Scenarios

1. Breadcrumbs for concept page
**Given** that I am on the 'List of Concepts' admin page
**When** I click 'KS1 maths point score' concept admin page
**Then** Then I am taken to the 'KS1 maths point score' concept admin page
And i see the 'breadcrumb' list of category tree pages that lead me to the 'KS1 maths point score' concept page

(Breadcrumbs seen should be: Home, Attainment, Progression between key stages, Key Stage 1 - 2 , KS1 maths point)

**Comment by RICHARDMACHEN1** [comment]
@benmemmott not sure the first sentence makes sence again......but maybe I am missing something?
