### ISSUE TITLE
Data tables page – give feedback

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#125]
### Allows a user to tell us why they prefer the data tables

**As** Find and Explore Product Owner
**I want** users to be able to explain why Find and Expore doesnt meet my requirements but the Data Tables do
**in order to** contribute to the imporvement of Find and Explore

### Scenarios

1. Submit feedback
**Given** I am on the data tables page
And i have populated the free text box with up to 100 words
**When** I select 'Submit'
**Then** my feedback should be sent to the DFE 
And I should see a message thanking me for my feedback
And the words I inputted should disappear

2. Word count box
**Given** I am on the data tables page
**When** I type 100 words into the text box
**Then** I should see ''0 words left'' in the word count box
And I should should not be able to add more words

3. Link to previous concept page
**Given** I am on the data tables page
And i got there from the 'FSM Past 6 Years' concept page
**When** I click the link to 'previous conncept page'
**Then** I should be returned to the 'FSM Past 6 Years' concept page

Note 1 - For 1. and 2.; discussed and Christina will try to embed Google Forms into the page to make this quicker - this may affect some of the functionality available but Rich accepts that.

Note 2 - For 3. this could just be a back link or possible a breadcrumb - whatever works easiest is fine.

Note 3 - As suggested by Christina: In mock-up, reverse the file download and feedback sections so the user is more likely to give feedback, then download the file.

**Comment by benmemmott** [comment]
[Data Tables Page V0_0.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/3120260/Data.Tables.Page.V0_0.pdf)

**Comment by RICHARDMACHEN1** [comment]
@benmemmott Scenario 3, in the 'given', should read 'And I a got **there** from'
