### ISSUE TITLE
Highlight staging environment

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#128]
As an anonymous or admin user
When I visit the staging site
I need to be given a visual cue that it is a staging environment (not production)
So I don't make changes in the wrong environment

We can check `Rails.env` for `:staging`/`:production`, and potentially do something like changing the colour and adding "staging" in bold to the header (or something better than that!).

**Comment by benmemmott** [comment]
UX OK'd by Rich:

Should appear on all staging from top level category page onwards.

[F&E Staging Warning.docx](https://github.com/DFE-Digital/npd-find-and-explore/files/3467525/F.E.Staging.Warning.docx)
