### ISSUE TITLE
Start page – email NPD Team

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#13]
### Describe the solution you'd like

**As an** external user
**I need** a contact email for the NPD Team
**in order to** ask questions

### Scenarios

**Given** I'm an anonymous user
**When** I go to the start page
**Then** see a link to email the data sharing team (data.sharing@education.gov.uk)

**Comment by benmemmott** [comment]
![13](https://user-images.githubusercontent.com/48209167/54368349-e17cac80-466b-11e9-9471-d7e0602cc1a8.JPG)
