### ISSUE TITLE
Search has 0 results in staging/production

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#130]
### Steps to reproduce

From the start page of Find & Explore
Enter the term "Ethnicity" into the search bar
Click "Search"

### Expected result

At least one concept result ("Ethnicity")

### Actual result

No results found

### Example

https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/search?sort=relevant&search=ethnicity

Should return the following concept:

https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/en/concepts/b8e647eb-ca99-4cdb-b1c5-9744adf0761c

### Notes

The categories loader errored out after the demographics sheet was loaded. Could this have prevented some reindexing?

**Comment by krios82** [comment]
The categories upload script may have crashed before reaching the point in which it generates indexes for categories and concepts.

To reindex from Rails console:
```
PgSearch::Multisearch.rebuild(category)
PgSearch::Multisearch.rebuild(Concept)
```

To reindex from bash console, as a rake task:
```
rake pg_search:multisearch:rebuild[Category]
rake pg_search:multisearch:rebuild[Concept]
```

**Comment by spikeheap** [comment]
👍 this is fixed in production
