### ISSUE TITLE
Start page – link to Data Tables

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#14]
### Describe the solution you'd like

**As an** experienced user who is used to the old system
**I want** access to the old Data Tables
**in order to** request data while I get used to the new system

### Scenarios

**Given** I'm an anonymous user on the start page
**When** I select to view the Data Tables
**Then** the *latest* version of the Data Tables XSLX file is downloaded

#### Admin/maintenance
**Given** I'm an authenticated NPD updater
**and** I'm in the NPD Find & Explore admin interface
**When** I upload a new version of the Data Tables XLSX file
**Then** the *latest* version of the Data Tables XSLX file is available on the start page

**Comment by spikeheap** [comment]
Should we use the Data Tables XLSX which was last uploaded into Find & Explore as the file to download. As I write this, it seems more like a no-brainer.

**Comment by spikeheap** [comment]
This depends on #45

**Comment by benmemmott** [comment]
![14](https://user-images.githubusercontent.com/48209167/54368651-6f589780-466c-11e9-91f6-9bb2fe70814b.JPG)

**Comment by RICHARDMACHEN1** [comment]
Not sure this is required just yet. RM
