### ISSUE TITLE
Admin area - make the full row a click target

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#145]
Clicking a row in the category/concept/data item list doesn't take you to the page. This requires you to click on the text within the box, which is a bit counter-intuitive given the highlighting. Could we update it to accept a click anywhere within the area?

https://user-images.githubusercontent.com/464482/57012111-cd314680-6bfc-11e9-989d-252aa1227653.gif

**Comment by spikeheap** [comment]
This is now fixed in prod 👍
