### ISSUE TITLE
Concept page  – Sensitivity pop-up box shows 'A to D'

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#152]
Sensitivity pop-up on all concept pages should read:

''Data is given a sensitivity scale. Items are rated from A to E with A being highly sensitive and E being low.''

**Comment by RICHARDMACHEN1** [comment]
Moved from 'done' to backlog as this issue is still occuring.

**Comment by DFEchristian** [comment]
Passed testing

![image](https://user-images.githubusercontent.com/52925065/61802763-f2fb6f80-ae28-11e9-8f8d-61f1600cbcf7.png)


![image](https://user-images.githubusercontent.com/52925065/61802804-03abe580-ae29-11e9-9d9c-1dbdfe113b2a.png)
