### ISSUE TITLE
[Data Tables Upload] – upload button not disabled/hidden on submit

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#156]
When you click the upload button a spinner is presented, however the upload button is still visible:

![upload_dt_no_feedback](https://user-images.githubusercontent.com/464482/57137526-035ef980-6da8-11e9-9b73-266b490c6986.gif)

### Expected

The upload button is hidden while the upload is in progress

**Comment by krios82** [comment]
<img width="1440" alt="Screen Shot 2019-07-31 at 15 49 25" src="https://user-images.githubusercontent.com/2742327/62222166-cdcbab80-b3aa-11e9-8405-fa95a60e0124.png">
