### ISSUE TITLE
Start page – date _next_ updated

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#16]
### Describe the solution you'd like

**As a** researcher
**I want** to see the next time (?) the NPD metadata is scheduled to be reviewed (?) and updated (?)
**in order to** help me understand when (either ?) new data will be available (or ?) the metadata could change.

This could be complicated. Do we publish the schedule for NPD updates, and do we mean the NPD metadata, NPD data. What's the subject of this date? Also... it's not the counterpart of "last updated".

### Scenarios

> TODO

**Given** [some setup, as a type of user]
**When** [I carry out some action]
**Then** [I expect something to happen]

**Comment by benmemmott** [comment]
Too complex for now. Closing and wishlisting.
