### ISSUE TITLE
Google Tag Manager not loaded in production

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#162]
### To reproduce

- Open the browser console view
- Visit https://s112p01-find-npd-data.azurewebsites.net/categories

### Expected

- No errors, Google Tag Manager is loaded

### Actual

The following console errors occur:
```
The script from “https://www.googletagmanager.com/gtm.js?id=GTM-M7CG53H” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.[Learn More] categories
```
and 
```
Loading failed for the <script> with source “https://www.googletagmanager.com/gtm.js?id=GTM-M7CG53H” (404)
```

**Comment by krios82** [comment]
The tag version wasn't published yet.

Fixed following this:
https://www.analyticsmania.com/post/google-tag-manager-404-error-gtm-js/

**Comment by spikeheap** [comment]
:+1: Let's close issues when we move them to done too
