### ISSUE TITLE
404 for fallback crown image

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#163]
### To reproduce

- In Microsoft Edge, visit https://s112p01-find-npd-data.azurewebsites.net
- Open the developer tools and visit the console

### Expected

- No 404s

### Actual

- `HTTP 404 (Not Found): https://s112p01-find-npd-data.azurewebsites.net/assets/images/govuk-logotype-crown.png`

The page still renders the crown image from the SVG, so this doesn't affect the visual style of the page in Edge.

**Comment by DFEchristian** [comment]
passed live test

![image](https://user-images.githubusercontent.com/52925065/61803122-87fe6880-ae29-11e9-90fa-6ac00d6df740.png)
