### ISSUE TITLE
Start page – start button

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#17]
### Describe the solution you'd like

**As a** user wanting to use Find & Explore
**I need** a start button
**in order to** get to the category hierharchy/search page

### Scenarios

**Given** I'm an anonymous user on the start page
**When** I click the start button
**Then** I'm taken to the home page top-level category list

**Comment by benmemmott** [comment]
![17](https://user-images.githubusercontent.com/48209167/54368945-f4dc4780-466c-11e9-954d-c3090d72fb5a.JPG)
