### ISSUE TITLE
[security] Cookie Without Secure Flag Set

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#175]
From the IT Health Check report:

> Cookie Without Secure Flag Set – ARRAffinity & _npd_find_and_explore_session

**Comment by spikeheap** [comment]
This may be resolved by the recent PR to force_ssl. Can be re-tested.

**Comment by spikeheap** [comment]
We are unable to resolve the `ARRAffinity` secure flag, as this is set by Azure infrastructure. It is only intended to be round tripped to the server, and doesn't contain secure information. The MS team seem reluctant to prioritise this, but have stated that it doesn't pose a risk.

For more, see the discussion at https://github.com/Azure/app-service-announcements-discussions/issues/26.

**Comment by krios82** [comment]
The `_npd_find_and_explore_session` part has been solved by the `force_ssl` PR in staging, will need to redeploy to production for this to take effect there.
