### ISSUE TITLE
[security] Old JQuery on login page

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#183]
From a call with Duncan:

> The admin sign-in page still uses an out-of-date JQuery library

> Vulnerabilities in jQuery Library - Vulnerabilities were identified in the version of the jQuery library used by the web application.

> BSI   recommends that the jQuery library be upgraded to the latest compatible  version.

![image005](https://user-images.githubusercontent.com/464482/57448769-18c59f00-7252-11e9-8097-4050efddaee0.png)

**Comment by krios82** [comment]
@benmemmott I would appreciate if you could test the admin area by just making sure everything still works.
With this fix I also found and fixed the issue that prevented creating and editing categories, so you may want to check that too.

**Comment by benmemmott** [comment]
Tested Cats and Concs - see Excel file on Slack. Everything looks OK. Seperately i will test Dat Items now. @cacquani : I may come back to you about this stuff as I need to understand where we are with how it SHOULD handle things like Data Items without a category. Cheers.
