### ISSUE TITLE
[security] Access to Administration Page Not Restricted

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#189]
> Access to Administration Page Not Restricted - The administration login page was found not to be locked   down to a whitelisted IP range.

> BSI   recommends that access to the admin pages are restricted to only trusted IP   ranges.

IP's are:

194.72.231.130
194.72.231.131
194.72.231.132
194.72.231.133  
217.38.175.49 
217.38.175.50
217.38.175.51 
217.38.175.52 
217.38.175.53

**Comment by krios82** [comment]
Emailed Ritesh Patel and John Carter for further details about the WAF/Application Gateway option and if/what they discussed with Ryan.

**Comment by benmemmott** [comment]
Met John Carter today. He's meeting Ritesh's team next Friday to talk about the long term solution which is still to be developed. FOr now, John has recommended that we redirect access via the ESFA forewall so that we can restrict via IP addy. He is speaking to Angie Paylor and he'll get back to us with what we ask for in a service request.

**Comment by DFEchristian** [comment]
Still waiting for a response

**Comment by DFEchristian** [comment]
@DFEchristian and @RICHARDMACHEN1 to speak to JC w/c 26/08 to progress this.

**Comment by DFEchristian** [comment]
John Carter stopped by yesterday to advise that he is working to implement a layer (with another team) to act as a filter for the IP addresses. This is effectively blocked as it now has an external dependency.

**Comment by DFEchristian** [comment]
JC advised that he is working on adding a filtering layer to block the IPs. This is effectively blocked while JC progresses this work.

**Comment by DFEchristian** [comment]
This is blocked by [#189](https://github.com/DFE-Digital/npd-find-and-explore/issues/189) which John Carter is on with. Once he has provided the solution we can bring this feature back into play and figure out the next steps.

**Comment by benmemmott** [comment]
IM'd John today to get an update on his visit to Coventry where the ESFA developers are. Will physically chase this afternoon if no reply.
