### ISSUE TITLE
[security] Incorrect Server Time (Azure Web App Service)

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#190]
From the BSI IT Health Check:

> Incorrect Application Server Time -   The time on the application server was found to be incorrect.

> BSI recommends   that the correct time should be set on the application server.

**Comment by spikeheap** [comment]
I've checked this on staging and production, and the server time is displayed as GMT, so it appears "wrong" when the user is in BST. The timestamp does say `+0000`, which is technically correct, but we may want to format the timestamp for the user's timezone.

**Comment by krios82** [comment]
Since the admin users will always be in UK time, we can just set the display time zone to GB.
