### ISSUE TITLE
Data Tables Loader doesn't remove obsolete Data Elements

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#192]
### Steps to reproduce
1. Ensure that at least one Data Element exists.
2. Remove that Data Element from the Data Tables Excel file.
3. Go to Import Data Elements admin page ([staging](https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/admin/data_elements/import)).
3. Upload the Data Tables file.

### Expected

1. Data Elements that were in the system but not in the new document are removed from Find & Explore.

### Actual

- Obsolete Data Elements remain in Find & Explore, and are not deleted

**Comment by benmemmott** [comment]
This relates to #203 and #268 #267

**Comment by DFEchristian** [comment]
This ticket cannot be progressed until [#334](https://github.com/DFE-Digital/npd-find-and-explore/issues/334) has been resolved.
