### ISSUE TITLE
Data Tables Upload – Display data entities affected by upload before commiting 

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#203]
### Allows admin user to check that changes are the ones they expected after a DT upload

**As a** admin user
**I want** to see how my DT upload will affect the data entities held within Find and Explore before I confirm I want to make the changes
**in order to** check that the changes made are the ones I expected

### Scenarios

1. Data Elements Added
**Given** I am viewing on the import data elements page
**And** i have pointed the browse button towards a valid Excel file that includes DE's that don't currently exist in Find and Explore
**When** I select 'Upload'
**Then** I am shown a list of DE's that will now be added to Find and Explore if 'confirm upload' is selected

2. Data Elements Removed
**Given** I am viewing on the import data elements page
**And** i have pointed the browse button towards a valid Excel file that doesn't include DE's that currently exist in Find and Explore
**When** I select 'Upload'
**Then** I am shown a list of DE's that will now be removed from Find and Explore if 'confirm upload' is selected

3. No Data Elements Affected
**Given** I am viewing on the import data elements page
**And** i have pointed the browse button towards a valid Excel file that includes no additions or deletions to existing data elements on Find and Explore
**When** I select 'Upload'
**Then** I am shown a message that 'No data elements added or deleted '
**And** the copy in temporary memory is deleted

4. Data Upload Confirmed
**Given** I am viewing the list of changes my prospective data tables could make
**When** I select 'Confirm Upload'
**Then** the system completes the uploads and makes the changes
**And** displays a message that the upload has succesfully completed

5. Data Upload not confirmed
**Given** I am viewing the list of changes my prospective data tables could make
**When** I select 'Cancel Upload'
**Then** the system discards the prospective upload
**And** displays a message that the upload has not been completed

Note 1: In case of either a) no data elements removed, but data elements have been added or b)  data elements have been removed, but no data elements have been added, then the box should be displayed, but it should state that 'No Data Elements will be added as a result of this upload' or 'No Data Elements will be removed as a result of this upload'. See UX designs.

Note 2: Data elements removed should show the breadcrumbs to the element to help the user understand where the item is currently kept.

Note 3: Data element names should include table and title (ie Alt_Provision_07-08_to_18-19.Age_Start).

Note 4: If more than 3 data items is included in either or both tables, then option should be included to collapse the table.

**Comment by benmemmott** [comment]
This story partly covers requirements originally in #45

**Comment by benmemmott** [comment]
UX Designs:
[Data Tables Upload Results _ 2 _ Added Only.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/3477255/Data.Tables.Upload.Results._.2._.Added.Only.pdf)
[Data Tables Upload Results _ 3 _ Deleted Only.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/3477256/Data.Tables.Upload.Results._.3._.Deleted.Only.pdf)
[Data Tables Upload Results _ 1 _ Added And Deleted.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/3477257/Data.Tables.Upload.Results._.1._.Added.And.Deleted.pdf)

**Comment by DFEchristian** [comment]
This ticket cannot be progressed until [#334](https://github.com/DFE-Digital/npd-find-and-explore/issues/334) has been resolved.
