### ISSUE TITLE
Detail page – Display if a data item won't be shared

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#210]
### Data items that can't be shared because of Departmental policy are marked up appropriately

**As a** NPD Data Owner
**I want** F&E Users to understand which data items we hold and of those, which can't be shared
**So that** users don't waste time planning or requesting that data

### Scenarios

**Given** I am on the 'Forenames' category page
**When** I select to view the Pupil Middle Name detail page
**Then** I see a message stating that data items in this concept cannot be shared for research

Note 1: The text should read:
**This data item is not available for research purposes**
This data item cannot be applied for as it is has an Identification risk rating of 1. The DFE has
committed to only use this data for internal purposes
(Ignore text in attached UX doc, just use for style and placing).

Note 2: UX doc
[NPD_Banner_UED_v1.0.docx](https://github.com/DFE-Digital/npd-find-and-explore/files/3427254/NPD_Banner_UED_v1.0.docx)

Note 3: Should just be front end work, so good for Pete and Christian to pick up on 25/07 (when I'm off)

**Comment by benmemmott** [comment]
[NPD_Banner_UED_v1.0.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/3427221/NPD_Banner_UED_v1.0.pdf)

**Comment by petelonsdale** [comment]
@benmemmott @RICHARDMACHEN1 @cacquani @DFEchristian 
I've created some options for the final solution for this based off the UX work that was completed previously. This was to ensure that our final idea would meet with GOV.UK style guides.

To discuss in more detail...

1. Top Banner - as per original placement
![banner-v1](https://user-images.githubusercontent.com/5918321/61875516-b68c4a00-aee2-11e9-9703-a0c3c18717de.png)


2. Side Banner - replaces the blue 'How to Access' banner which might work better
![banner-v2](https://user-images.githubusercontent.com/5918321/61875554-cdcb3780-aee2-11e9-96c7-a12318f3ddd3.png)


3. Side Banner HO style - Using Home Office styling
![banner-v3](https://user-images.githubusercontent.com/5918321/61875599-e89dac00-aee2-11e9-82c5-276a3105cccd.png)
 

4. Warning style - Using original GOV.UK warning styling.
![banner-v4](https://user-images.githubusercontent.com/5918321/61875671-0e2ab580-aee3-11e9-84ac-be89d88c42e3.png)

**Comment by krios82** [comment]
Identifiability < 3:

<img width="1440" alt="Screen Shot 2019-07-29 at 14 26 38" src="https://user-images.githubusercontent.com/2742327/62052186-e8681e00-b20c-11e9-8a6d-94a62ea31442.png">

Identifiability > 3:

<img width="1440" alt="Screen Shot 2019-07-29 at 13 35 36" src="https://user-images.githubusercontent.com/2742327/62048838-c4550e80-b205-11e9-936c-5f7bcd6a7231.png">
