### ISSUE TITLE
All pages – correct page titles on tab

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#217]
### Correct page title is displayed on the tab

**As a** F&E user who uses screeneader software
**I want** the page title to be correct
**in order to** understand, broadly, what is on that page

### Scenarios

**Given** that I am an anonymous user
**And** I use JAWS screenreader
**And** I am on the 'Number of exclusions during academic year' page
**When** I review the page title 
**Then** I read ''Number of exclusions during academic year - NPD Find and Explore''
(Format is ''<Name of page you areon> - NPD Find and Explore) 

Note 1: Jane Dickinson confirmed this is the preferable solution
Note 2: Accessibility Doc included below

**Comment by benmemmott** [comment]
![page titles](https://user-images.githubusercontent.com/48209167/61640229-df1f0480-ac94-11e9-8982-4133c7796f14.JPG)

**Comment by DFEchristian** [comment]
Passed testing. 

![image](https://user-images.githubusercontent.com/52925065/61787865-a4d67400-ae08-11e9-8fdc-45451bd4480d.png)

**Comment by DFEchristian** [comment]
Closed as released now.
