### ISSUE TITLE
[Security] – Cookie without secure flagset

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#224]
See below for issue with Cookie:

![cookie 1](https://user-images.githubusercontent.com/48209167/61718888-bdd51b80-ad5b-11e9-8018-cc9032741c6f.JPG)

![Cookie 2](https://user-images.githubusercontent.com/48209167/61718892-c2013900-ad5b-11e9-8641-f8f8ed274e70.JPG)

**Comment by DFEchristian** [comment]
Closed as released now.
