### ISSUE TITLE
Admin page – New concepts page, Category list narrows down as you type

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#236]
### The Category list on the New Concepts page currently selects one category as you type - it should instead, narrow the displayed list to mach the text you have imput, on the fly

**As a** an F&E admin user
**I want** to have the possible categories available for me to select, narrow down as I type text into the box
**in order to** if I only know the start of a category's title I can quickly and easily navigate to it

### Scenarios

Scenario 1 - List narrows down
**Given** That I am an F&E admin user and I am logged in
**And** I am on the New Concepts page
**When** type 'School' into the 'Category' free text box
**Then** the list below it is reduced to only display those categories that start with 'School'.

**Comment by cacquani** [comment]
<img width="1440" alt="Screen Shot 2019-08-06 at 11 58 49" src="https://user-images.githubusercontent.com/2742327/62534739-b163bf00-b841-11e9-914e-0f1beeb5f18a.png">
<img width="1440" alt="Screen Shot 2019-08-06 at 11 58 54" src="https://user-images.githubusercontent.com/2742327/62534754-b6c10980-b841-11e9-8f60-82a89285b29a.png">
<img width="1440" alt="Screen Shot 2019-08-06 at 11 58 59" src="https://user-images.githubusercontent.com/2742327/62534772-bd4f8100-b841-11e9-96b8-f3683906141a.png">
<img width="1440" alt="Screen Shot 2019-08-06 at 11 59 19" src="https://user-images.githubusercontent.com/2742327/62534787-c50f2580-b841-11e9-8cd7-9f436242a96b.png">

**Comment by krios82** [comment]
<img width="1440" alt="Screen Shot 2019-08-06 at 14 27 32" src="https://user-images.githubusercontent.com/2742327/62543768-6b652600-b856-11e9-96e0-4175b185d7c8.png">
<img width="1440" alt="Screen Shot 2019-08-06 at 14 27 44" src="https://user-images.githubusercontent.com/2742327/62543778-6ef8ad00-b856-11e9-8fb6-180a20a9faa9.png">
<img width="1440" alt="Screen Shot 2019-08-06 at 14 27 53" src="https://user-images.githubusercontent.com/2742327/62543785-728c3400-b856-11e9-8385-7d045af3bdfe.png">
