### ISSUE TITLE
Detail page – earliest date collected

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#24]
### Detail page shows the earliest date when that concept was collected from

**As a** researcher
**I want** to see the earliest date that a concept was collected from
**in order to** I know from what year the concept can be used for analysis

### Scenarios

**Given** I am an anonymous user
**When** I click to view the 'FSM past 6 years' detail page
**Then** in the summary I see a year for when that concept was first collected 
(all start dates for data items are 2019, 2015, 2012, 2014 and 2011, so '2011' would be displayed).

**Comment by krios82** [comment]
For now used "Collected from" for the label and "The earliest academic year data was collected from." for the tooltip, is that OK or we need better copy? 

<img width="1059" alt="Screen Shot 2019-03-25 at 14 53 01" src="https://user-images.githubusercontent.com/2742327/54929666-dba98580-4f0d-11e9-92d9-b7c3cda14b01.png">

**Comment by petelonsdale** [comment]
@cacquani yeah that sounds fine to me 👍
