### ISSUE TITLE
Detail page – Red banner wording change and applicable to ID Risk 2

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#241]
### The red banner that warns applicants that data is sensitive needs to have its wording changed to be more accurate and apply to ID Risk 2 items as well.

**As a** NPD Data Owner
**I want** F&E Users to understand which data items we hold and of those, which cannot be accesed via ONS
**So that** users don't waste time planning or requesting that data if they want to access it in a data lab

### Scenarios

Scenario 1 - Banner appears on ID RIsk 1 concepts
**Given** I am on the 'Forenames' category page
**When** I select to view the Pupil Middle Name detail page
**Then** I see a message stating that data items in this concept cannot be accessed via ONS

Scenario 2 - Banner appears on ID Risk 2 concepts
**Given** I am on the 'Pupil reference numbers' category page
**When** I select to view the Unique Pupil Number detail page
**Then** I see a message stating that data items in this concept cannot be accessed via ONS

Note 1: This is essentially an amendment to story #210 by Gwen
Note 2: Wording should read:
"The data in some or all of these variables has an identification risk of 1 or 2.  As a researcher, this data is only available if you meet one or more of **4 exemptions** following a successful application."
Note 3: ''4 exemptions'' (bolded above) shuold link to: https://www.gov.uk/guidance/how-to-access-department-for-education-dfe-data-extracts

**Comment by krios82** [comment]
<img width="1440" alt="Screen Shot 2019-07-31 at 15 06 12" src="https://user-images.githubusercontent.com/2742327/62218638-c4d7db80-b3a4-11e9-9d8e-9d3d4099f641.png">

**Comment by petelonsdale** [comment]
@benmemmott Sorry to be a pain but should 'This data in some or all of these variables' read as '**The** data in some or all of these variables' ?

**Comment by benmemmott** [comment]
@petelonsdale You're not being a pain! Absolutely correct and I've changed it. Thanks.
