### ISSUE TITLE
Detail page – concept identifiability rating

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#26]
### Detail page shows the idetificability rating for the data items that make up that concept

**As a** researcher
**I want** to see the identifiability rating for all the items that make up that concept
**in order to** understand how identifiable the concept is and therefore how it might affect my application

### Scenarios

**Given** I am an anonymous user
**When** I click to view the 'FSM past 6 years' detail page
**Then** I see a summary identifiability rating for all the dat items in that concept

Note: As far as we know at the moment, all data items in a concept should have the same identifiability rating.

**Comment by spikeheap** [comment]
Just for clarity, this is _not_ an attribute on `concept`, it's derived from the data items contained within it.

**Comment by benmemmott** [comment]
![26](https://user-images.githubusercontent.com/48209167/54369709-49cc8d80-466e-11e9-9a2d-70c57b0e62ac.JPG)

**Comment by benmemmott** [comment]
Query over how we show a concept's aggregated ID rating when there may be more than one. Many ways we can slice it including making CIN\CLA\ETC a different category. We will know more when the data is loaded into F&E. Paused for now.
