### ISSUE TITLE
Detail page – aggregated count of records

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#27]
### Detail page shows an aggregated count of records for the items that make up that concept

**As a** researcher
**I want** to see an aggregated count of records for the data items that make up a concept
**in order to** understand how big a resource the data returned would be for my analysis

### Scenarios

**Given** I am an anonymous user
**When** I'm click to view the 'FSM past 6 years' detail page
**Then** I see an aggregated count of records for that concept's data items

**Comment by spikeheap** [comment]
This has become an epic because it requires thought on how we extract it from the NPD, and the process to build up the numbers for each data item. Do we need to collect this over multiple years, etc?

**Comment by benmemmott** [comment]
![27](https://user-images.githubusercontent.com/48209167/54369776-6cf73d00-466e-11e9-917c-47692d708333.JPG)
