### ISSUE TITLE
Admin concept page – When a container is deleted its contents are distributed within the Category Tree

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#276]
### If a container (Category, or Concept) is deleted that contains other objects (Categories, Concepts or Data Elements), then those data items are pmoved elsewhere in the Category Tree systematically.

**As a** F&E admin user
**I want** objects that were in the container I'm deleting to end up somewhere I can get to
 **in order to** stop me inadvertantly deleting valid 'things'

### Scenarios

1. Deleting a Concept that contain Data Elements
**Given** I and a admin user who is logged in
**And** I am viewing the 'Concepts' page
**And** I have searched to the 'C1' concept
**When** I select 'destroy' and 'confirm'
**Then** the data items 'DE1', 'DE2', and 'DE3' are moved to the 'No Concept' container

2. Deleting a Category that contains a Concept
**Given** I and a admin user who is logged in
**And** I am viewing the 'Concepts' page
**And** I have searched to the 'LC1' category
**When** I select 'destroy' and 'confirm'
**Then** the Concept 'C1' (and contents and relationships) is moved to the 'No Category' container.

3. Deleting a Category that contains Category
**Given** I and a admin user who is logged in
**And** I am viewing the 'Concepts' page
**And** I have searched to the 'MC1' category
**When** I select 'destroy' and 'confirm'
**Then** the Category 'LC1' (and its contents and relationships) is moved to the top level of the Category tree.

Note 1: Story required after I placed 'Exclusions_05-06_to_17-18.PLAA' in Test Top Level Category\Test Mid Level Category 2\Test Low Level Category 2\Test Concept 5, then deleted Test Concept 5. The data item was deleted also.

Note 2: The scenarios in this story do not relate to the actual F&E information architecture - that was too complex to make a relatable example. Below is the starting point of an imagined, simple table (including Top Category 1, Mid Category 1, Low Category 1, Concept 1 and Date Entities 1 to 3). The three examples below that relate to the thre scenarios. When we test, I'll build this structure in Staging.

**Comment by benmemmott** [comment]
Example starting point
![SnipImage](https://user-images.githubusercontent.com/48209167/62717002-fb43d500-b9fa-11e9-92aa-92ddf84238cd.JPG)

**Comment by benmemmott** [comment]
1. Deleting a Concept that contain Data Elements
![SnipImage(2)](https://user-images.githubusercontent.com/48209167/62717139-41993400-b9fb-11e9-9e9f-8819d6ada8e8.JPG)

**Comment by benmemmott** [comment]
2. Deleting a Category that contains a Concept
![SnipImage(4)](https://user-images.githubusercontent.com/48209167/62717251-75745980-b9fb-11e9-978d-11157df4c333.JPG)

**Comment by benmemmott** [comment]
3. Deleting a Category that contains Category
![SnipImage(6)](https://user-images.githubusercontent.com/48209167/62717339-9fc61700-b9fb-11e9-9312-c91132569d78.JPG)

**Comment by DFEchristian** [comment]
@RICHARDMACHEN1 please can you confirm if this has released?

**Comment by DFEchristian** [comment]
Confirmed with @cacquani that this has been released.
