### ISSUE TITLE
Detail page – aggregated derivation info

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#28]
### Detail page shows aggregated derivation info for the data items that make up that concept

**As a** researcher
**I want** to see aggregated derivation information for the data items that make up that concept
**in order to** understand how the data items in that concept are created and factor that into my analysis

### Scenarios

**Given** I am an anonymous user
**When** I click to view the 'FSM past 6 years' detail page
**Then** I see 

BR1: ''Derivation information'' = Concept it is derived from?
NEEDS CONSIDERATION: Can items within a concept be derived differently? How do we show that if so? What to show if not derived?

**Comment by spikeheap** [comment]
This is an epic because we need to consider how we capture this information. It's not available on the data tables...

**Comment by benmemmott** [comment]
![28](https://user-images.githubusercontent.com/48209167/54369887-96b06400-466e-11e9-933a-f56f15f3c431.JPG)

**Comment by benmemmott** [comment]
After Story Issue meeting decided this was probably too complex for MVP. Closing and wishlisting.
