### ISSUE TITLE
Detail page – concept sensitivity rating

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#29]
### Detail page shows the sensitivity rating for the data items that make up that concept

**As a** researcher
**I want** to see the sensitivity rating for the data items that make up that concept
**in order to** understand how sensitive the concept is and therefore how it might affect my application

### Scenarios

**Given** I am an anonymous user
**When** I click to view the 'FSM past 6 years' detail page
**Then** I see a summary sensitivity rating for the data items that make up that concept

Note: As far as we know at the moment, all data items in a concept should have the same identifiability rating.

**Comment by benmemmott** [comment]
Query over how we show a concept's aggregated sensitivity rating when there may be more than one. Many ways we can slice it including making CIN\CLA\ETC a different category. We will know more when the data is loaded into F&E. Paused for now.

**Comment by krios82** [comment]
For now, show the maximum sensitivity value when data items have different values.
