### ISSUE TITLE
Detail page – aggregated data type(s)

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#30]
### Detail page shows aggregated types for the items that make up that concept

**As a** researcher
**I want** to see an aggregated data type for the items that make up that concept
**So that I** can factor that information into how I plan my analysis if i use items within this concept

### Scenarios

1.  All data types are same
**Given** I am an anonymous user
**And** I click to view the 'FSM past 6 years' detail page (where all data types are the same)
**Then** I see an the data type for the data items that make up this concept
(In this case 'Categorical (dichotomus)')

2.  Multiple data types
**Given** I am an anonymous user
**When** I click to view the '?' detail page (where there are multiple data types)
**Then** I see an aggregated data type for the data items that make up this concept
(for all concepts that have more than one data type: 'Multiple')

BR1: 4 types are....

**Comment by benmemmott** [comment]
![30](https://user-images.githubusercontent.com/48209167/54424289-7afa9b80-470a-11e9-82e7-46ee7e1a5f32.JPG)

**Comment by spikeheap** [comment]
Blocked pending either:
- Simone's efforts to add this to the Data Tables
- Ingesting Fields by Academic year
