### ISSUE TITLE
All pages under home - add search box to gov.uk banner

### ISSUE THREAD

**Issue by DFEchristian** [DFE-Digital/npd-find-and-explore#305]
### Every page beyond the home page (ie the Top Level Category page) should have a search box

**As a** F&E user
**I need ** to be able to search on any page 
**in order to** always be able to start my search again without having to retrun to the home page

### Scenarios

**Given** I am on the Absence & Exclusions category page
**When** I select the Absence sub category
**Then** I see a search box in the top right hand corner of the screen 
**And** is contains the word 'Search'

Note 1: UX slide included below

**Comment by benmemmott** [comment]
![image](https://user-images.githubusercontent.com/48209167/64324924-23553280-cfbf-11e9-9363-87efcdbbc694.png)

**Comment by benmemmott** [comment]
Tested and passed.
