### ISSUE TITLE
Bug - Investigate why 986 Data Elements are orphaned on Prod (and pronbably Stage)

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#309]
We believe there are 986 homeless Data Elements in Prodcution - and probably Staging (see separate ticket)

We need to work out how this happened - was it a result of:

- Manual error (deleting concepts?)
- Database or code error
- Something else

Homeless elements can be seen in Prod Admin if you go to Concepts page and search 'No Concepts'.

We have a date of 'Mon 5th Aug 2019 15:16:21' when we think they were made homeless

Two examples if needed are: NFTYPE and ToE_CODE, both for year 7.

**Comment by DFEchristian** [comment]
This has been fixed and released.
