### ISSUE TITLE
Bug - Identify and fix why Staging isn't showing all homeless Data Elements

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#311]
As per #309 a large number of Data Elements are missing from Production and Staging. Issue is that while you can see them in 'No Category\No Concept' on Admin, you can't see them at all in Staging (use examples of NFTYPE or ToE_CODE for Year 7 to see this across Prod and Staging).

Need to identify why they aren't showing up in Staging.

**Comment by DFEchristian** [comment]
This is working to spec due to the way the DBs (staging and prod) are designed.
