### ISSUE TITLE
Upload Categories Function - Let me upload a non-IAD - resulting in all Categories being removed from F&E

### ISSUE THREAD

**Issue by RICHARDMACHEN1** [DFE-Digital/npd-find-and-explore#312]
@benmemmott @cacquani I made a mistake when I was trying to test the Data Table uploader functionality. Instead I tried uploading the DTs into the Category Uploader:
Admin Tool - it enabled my to choose and upload a Non-Information Architecture Document - resulting in the F&E category page not showing any categories.
![Bug - IAD Upload (acceped my flexi)](https://user-images.githubusercontent.com/48243847/63804210-95b67a80-c90e-11e9-84af-42a7d3502548.PNG)
![Bug - IAD Upload (acceped my flexi) - resulting in all categories being deleted](https://user-images.githubusercontent.com/48243847/63804221-9cdd8880-c90e-11e9-8152-76426efd948d.PNG)
Is this the behaviour we expected? Or should there have been some sort of 'warning' / 'error' message liek we have with the Data Tables uploader? I guess the simple solution is just to re-load the IAD if someone makes this mistake in teh future?

**Comment by benmemmott** [comment]
IA validation has sorted this in #315 #314
