### ISSUE TITLE
Top level categories page – make this start page

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#316]
### We need to remove the current start page and make the top level categories page the new start page

**As a** F&E user
**I want** to see the top level categories page as the first thing i encounter once I opt to start the service
**in order to** move through the system in a sensible and ordered manner

### Scenarios

**Given** I am on the DFE 'Apply for data page'
**When** I click '<insert final text for link>'
**Then** I am taken to the top level categories page

Note 1: Current start page is here: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net (and can be seen in attachment below)
Note 2: New start page will look like this: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories but the URL should be https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/
Note 3: Story links to #289 where we will ask Comms team to add some text to this page: https://www.gov.uk/guidance/how-to-access-department-for-education-dfe-data-extracts.

**Comment by benmemmott** [comment]
![old start page](https://user-images.githubusercontent.com/48209167/64102511-0d9a0000-cd68-11e9-8925-61ee5b37b170.JPG)

**Comment by DFEchristian** [comment]
This ticket cannot be progressed until [#314](https://github.com/DFE-Digital/npd-find-and-explore/issues/314) has been resolved.
