### ISSUE TITLE
Detail page – data item name

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#32]
### Detail page displays data item title and description

**As a** researcher
**I want** see the name of the data item as it is dipsplayed in the NPD 
**in order to** use the exact name when i request data

### Scenarios

**Given** I am an anonymous user
**When** I click to view the 'FSM past 6 years' detail page
**Then** I see the 'FSM6' data item title

**Comment by spikeheap** [comment]
This needs to wait until we've loaded concepts in and done some analysis of how different/how many data items there are within each one.

This needs some thought as to whether we need a "description" on each data item, or "notes" that explain subtle variations (and are potentially option).

**Comment by spikeheap** [comment]
The data item "name" needs to contain the table/column address, e.g. `KS2_Pupil.FSM_6`

**Comment by benmemmott** [comment]
Also, larger question of whether each data item should have its own description or whether the concept description is all that's needed (in theory, the latter is true but testing showed that usersd wanted to see a separate description - however, this maybe them not 'getting' the idea of a concept - we need to signpost this better.

**Comment by benmemmott** [comment]
![32](https://user-images.githubusercontent.com/48209167/54424986-1f311200-470c-11e9-8214-db7f89f618cc.JPG)
