### ISSUE TITLE
Create Accesibility Page

### ISSUE THREAD

**Issue by DFEchristian** [DFE-Digital/npd-find-and-explore#320]
https://www.gov.uk/service-manual/helping-people-to-use-your-service/publishing-information-about-your-services-accessibility

> Publishing an accessibility page is part of meeting the new accessibility regulations that apply to public sector websites and apps. The full name of the new regulations is the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

**Tasks**
1. Add the Accessibility page from the Prototype to the live service - https://find-npd-data.herokuapp.com/accessibility
2. Create link in footer to be able to access the page throughout the service

**Comment by DFEchristian** [comment]
@petelonsdale and @benmemmott  please can you add the details/story to this ticket?

**Comment by petelonsdale** [comment]
This will need breaking out into 3 tasks - I think :)

Create Prototype with draft content - Done - https://find-npd-data.herokuapp.com/accessibility
Review content (For @benmemmott  and @RICHARDMACHEN1 )
Build page into service and add link in Footer (for @cacquani )

**Comment by tmarsdn** [comment]
@benmemmott The 'online form' link is dead on the 'Accessibility page. When selecting the link, it just navigates back to the top of the page.

Check the section on the attached image on the accessibility page: 

![online form link](https://user-images.githubusercontent.com/53817849/64518946-1a2fd280-d2eb-11e9-9de2-16a27ecba506.png)

**Comment by DFEchristian** [comment]
Closed in error so re-opened.

**Comment by benmemmott** [comment]
Tested and passed now.

**Comment by DFEchristian** [comment]
This is blocked by [#344](https://github.com/DFE-Digital/npd-find-and-explore/issues/334).
