### ISSUE TITLE
Information tooltip icon display issue on the NPD website

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#335]
**Tested on staging**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
--------------------------
1. Navigate to: Home > Absence and exclusion > Exclusions > Pupil exclusion history > Number of fixed exclusions
2. Notice the information icons are not displayed correctly for 'Sensitvity' and 'Identifiability' in the Data elements table

Please see attached image.

**This issue is also present on the following pages:**
--------------------------------------------------------
* Home > Absence and exclusion > Exclusions > Pupil exclusion history > Number of fixed exclusions

* Home > Absence and exclusion > Exclusions > Pupil exclusion history > Permanent exclusion indicator (The information tooltip is shown below the header)

... The issue seems to be present in most pages that contain the table.

![information icon issue](https://user-images.githubusercontent.com/53817849/64522069-199a3a80-d2f1-11e9-92d6-381568758485.png)

**Comment by benmemmott** [comment]
Tested and passed.
