### ISSUE TITLE
Table overflowing the page, display issue on the NPD website

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#337]
**Tested on staging**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
-----------------------
1. Navigate to: Home > Absence and exclusion > Exclusions > Exclusion details > Term exclusion started
2. Notice the table overflows the page

Please see attached image.

**This issue is also present on the following pages:**
----------------------------------------------------------
* Home > Absence and exclusion > Exclusions > Exclusion details > Start date
* Home > Absence and exclusion > Exclusions > Exclusion details > Year group
* Home > Absence and exclusion > Exclusions > Exclusion details > Number of sessions excluded from

... The issue seems to be present in most pages that contain the table.

![table overflow issue](https://user-images.githubusercontent.com/53817849/64522473-f459fc00-d2f1-11e9-8813-2dc3b09ecb5c.png)

Also in device view (Iphone X in Chrome Dev tools):

Part 1 and part 2 showing the table.

**Part 1**
-------
![Mobile View Part 1](https://user-images.githubusercontent.com/53817849/64524605-c7f4ae80-d2f6-11e9-881c-e60ad9cef7ba.png)

**Part 2**
----------
![Mobile View Part 2](https://user-images.githubusercontent.com/53817849/64524614-ccb96280-d2f6-11e9-8a1f-1ca356c244da.png)

**Comment by DFEchristian** [comment]
Discussed with Rich and this needs fixing BEFORE launch. Have asked Pete to look at it ASAP.
