### ISSUE TITLE
Sensitivity and Identification information tooltips are not present in mobile view

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#338]
**Tested on staging**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories
**Browser**: Chrome
**OS**: Windows 10 + Chrome Dev Tools in Iphone X emulator 

**Steps to reproduce**
------------------------
1. Navigate to: Home > Attainment > Number of qualifications achieved > KS4 - Total A-Levels (excluding General Studies and VCEs)
2. The information tooltips are not present for both the Sensitivity and Identification columns in mobile view, but they are present in desktop view

Please see attached image.

![Information tooltip not present in mobile view](https://user-images.githubusercontent.com/53817849/64523721-e063c980-d2f4-11e9-8672-f6811bad18d4.png)

**Comment by DFEchristian** [comment]
Discussed with Rich and happy for this to be addressed post launch.
