### ISSUE TITLE
Search on any criteria and sort by 'Recently added' or 'Recently updated' and they both produce the same order of results

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#342]
**Tested on staging**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
---------------------
1. On the 'Home' page input 'Age' into the search field
2. Select 'Recently added' in the 'Sort By' drop down
3. You will be presented with the results that are in recently added order
4. Now select 'Recently Updated' in the 'Sort By' drop down
5. Notice that the order has not changed and are still displayed in the same order. I have tested this with multiple search results and both options produce the same results

**Comment by benmemmott** [comment]
Another question is: ''Recently added'' is the default return - is this actually it, or is it relevance (relevance as decided by our search rules?).
