### ISSUE TITLE
Search with no details produces duplicate message

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#343]
**Tested on staging**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
------------------------
1. On the 'Home' select the 'Search' button with no input criteria
2. Notice that you get the duplicate message in the results of 'No results found'

Please see attached image.

![duplicate message](https://user-images.githubusercontent.com/53817849/64600619-63e3f000-d3b3-11e9-9287-27fb2f36dd27.png)

**Comment by DFEchristian** [comment]
Discussed with Rich and happy for this to be addressed post launch.
