### ISSUE TITLE
Low contrast on 'Edit Absence' button

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#346]
**Tested on staging (Admin)**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/admin/categories/363fbe54-89b8-4a70-8f5f-fdf8c7e35a86
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
------------------------
1. Navigate to Home > Absence and exclusion > Absence
2. Notice that the contrast is low on the 'Edit Absence' button, this has been flagged within the accessibility testing tool

Please see attached image.

![low contrast](https://user-images.githubusercontent.com/53817849/64613054-255b2f00-d3cd-11e9-9461-86b08376683c.png)

**Comment by DFEchristian** [comment]
Discussed with Rich and happy for this to be addressed post launch.
