### ISSUE TITLE
Dropdown issue loading in and lag on 'Data Elements' drop down

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#347]
**Tested on staging (Admin)**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/admin/concepts/c495994e-ac32-4338-8694-3752fe8e13ff/edit
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
------------------------
1. Navigate to https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/admin/concepts/c495994e-ac32-4338-8694-3752fe8e13ff/edit
2. There is a delay in the drop downs loading in (You can replicate this by refreshing the page)
3. Select the 'Data Elements' dropdown
4. Notice the lag on the drop down, if you select the 'Category' drop down, that is working as expected

Please see attached video

[Dropdown issue.zip](https://github.com/DFE-Digital/npd-find-and-explore/files/3595588/Dropdown.issue.zip)

**Comment by DFEchristian** [comment]
Discussed with Rich and happy for this to be addressed post launch.
