### ISSUE TITLE
Detail page – data item educational phases

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#37]
### Allows the user to see which the educational phases the data item is collected during

**As a** researcher
**I want** see which educational phases a data item covers
**in order to** understand which phases of education the item can be used to analyse

### Scenarios

**Given** I am an anonymous user
**And** I have clicked to view the 'FSM' detail page
**When** I look at the 'FSM Eligible' data item
**Then** I see a list of educational phases that the data item is collected during
(here, Early years, KS1, KS2, KS3, KS4, KS5)

**Comment by spikeheap** [comment]
This depends on new data being added to the Data Tables. Simone has created a new column to collect this.

**Comment by benmemmott** [comment]
![37](https://user-images.githubusercontent.com/48209167/54425405-26a4eb00-470d-11e9-9861-75606c03d3fe.JPG)

**Comment by krios82** [comment]
The education phases will be a comma-separated list.
Possible values: `EY`, `PRI`, `SEC`, `P-16`
