### ISSUE TITLE
Detail page – data item code meaning

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#38]
### Allows the user to see the meanings of the codes used in the data item's collection

**As a** researcher
**I want** to see the meaning of a data item's codes when relevant
**in order to** I can begin to plan my analysis

### Scenarios

**Given** I am an anonymous user
**And** I am on the 'Ethnicity' concept page
**When** I click to view the codeset for the 'Ethnicity' data item
**Then** I see a pop up window containing the possible codes used in its return and an explanation of what they stand for (see screengrab below)

NEEDS CONSIDERATION: Do any have so many codes that they break the layout?

**Comment by petelonsdale** [comment]
![image](https://user-images.githubusercontent.com/5918321/54276919-61304b80-4586-11e9-86de-662a3c8657f1.png)

**Comment by krios82** [comment]
In the data tables in most tables we have a "Values" or "Allowed Values" field.
This field is currently pretty badly formatted, but for now just use the existing value whenever not nil.
Do not even show the `Codeset` link when the value isn't in the database.
