### ISSUE TITLE
Detail page – data item notes

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#39]
### Allows the user to see a description of an individual data item

**As a** researcher
**I want** to see a description of each data item
**in order to** understand what that data item is

### Scenarios

**Given** I am an anonymous user
**And** I am on the 'FSM past 6 years' detail page
**When** review the 'FSMEligible' data item 
**Then** I see a description of it
(Description: 'Pupil recorded as eligible for Free School Meals on Census day. From 2012/13, set to 'true' if a pupil has an FSM period with a start date and end date blank or end date on or after census date which means they are FSM eligible on Census day.')

**Comment by spikeheap** [comment]
This needs to wait until we've loaded concepts in and done some analysis of how different/how many data items there are within each one.

This needs some thought as to whether we need a "description" on each data item, or "notes" that explain subtle variations (and are potentially option).

**Comment by benmemmott** [comment]
![39](https://user-images.githubusercontent.com/48209167/54425494-61a71e80-470d-11e9-9b19-d28c4095ae87.JPG)
