### ISSUE TITLE
Detail page – which collections data item ingested via

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#40]
### Allows the user to understand which collection the data item came in via

**As a** researcher
**I want** to see what data collection a data item was ingested via
**in order to** understand the full collection context of the item

### Scenarios

**Given** I am an anonymous user
**And** I am on the 'FSM past 6 years' detail page
**When** I review the 'FSM6' data item
**Then** I see the collection the item was ingested via (?)

**Comment by spikeheap** [comment]
This isn't in the current prototype, so needs some thought about whether it'd be useful or not
