### ISSUE TITLE
Detail page – data item sensitivity  and identification risk rating

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#42]
### Concept page shows a data item's sensitivity and Identification Risk rating in line, not as part of the aggregate

**As a** researcher
**I want** to see the sensitivity and identification risk rating of an individual data item
**in order to** understand how sensitive that data item is and therefore how it might affect my application

### Scenarios

**Given** I am an anonymous user
**And** I am on the Free School Meals (FSM) category page
**When** I click to view the 'Eligibile for free school meals in the past 6 years' detail page
**Then** For KS4_Pupil.FSM6_P i see a Sensitivity score of C and a Identification risk of 5

Note 1: See attached UX page from Pete for design
Note 2: These two columns should replace Collection term and Educational phase (we may bring these columns back at a later date)
Note 3: Also to be removed are the Sensitivity and Identifiability aggregate scores: This will leave 'Data Type' and 'Collected from' in the aggregate.

**Comment by benmemmott** [comment]
This links to #29  and may not be needed if we confirm that all data items within a concept have the same sensitivity ratings.

**Comment by petelonsdale** [comment]
Screenshot attached of proposed solution. Agreed to also change **Identifiability** to **Identification Risk** as Simone pointed out that that is what is currently used.

![localhost_3001_filters_detail-sensitivity-alt1](https://user-images.githubusercontent.com/5918321/62131323-e36da200-b2d2-11e9-9ac1-0f32d9365487.png)

**Comment by DFEchristian** [comment]
Closed as released now.
