### ISSUE TITLE
Update Data Items in F & E

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#45]
### Allows a NPD team member to update the system via a validated copy of the data tables

**As a** NPD team member
**I need** to update the meta-data held with the system
**in order to** maintain its accuracy and ensure it remains useful to our users

-----
Validate format - bad file format
**Given** that I am a logged in Admin User
**When** I submit a Data Table that is a PDF file
**Then** I recieve a message saying that the file format is not permitted
And I see a button that returns me to the admin page

Validate format - bad structure
**Given** that I am a logged in Admin User
**When** I submit a Data Table that has no NPDAlias column
**Then** I recieve a message saying that the file strcuture is not permitted due to no NPDAlias column being present
And I see a button that returns me to the admin page

Validate format - too large
**Given** that I am a logged in Admin User
**When** I submit a Data Table that ?GB or over in size
**Then** I recieve a message saying that the file size is not permitted 
And I see a button that returns me to the admin page

-----
Data validation - no changes
**Given** that I am a logged in Admin User
**When** I upload a Data Tables file that does not remove, add or change any data items
**Then** the system returns a message that no changes have been submitted
And I see a button that returns me to the admin page

----
Data validation - do not carry out changes
**Given** that I am a logged in Admin User
**When** I upload a Data Tables file that changes a data item
And I am presented with the option to carry out the prospective changes
And I choose not to make the changes
**Then** the system deletes the prospective Data Tables
And returns me to the Admin Page

**Comment by spikeheap** [comment]
This will likely want some refactoring after #56

**Comment by benmemmott** [comment]
After the stories issue Jon added a task to the board to reconsider this next week, getting Gwen et al involved. I will aim to do a Visio of the maintenance journey by early next week.

**Comment by benmemmott** [comment]
[FandE Maint Journey v0_0.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/3089942/FandE.Maint.Journey.v0_0.pdf)
Process map of user and system actions is here.

**Comment by benmemmott** [comment]
Update:
- Validate format - bad file format - has been completed
- Validate format - bad structure has been split out into two stories: #267 (NPD alias) and #268 (expected tabs)
- The two Data Validation stories have been included in story #203 without the 'Changes' requirement which is too complex for MVP
