### ISSUE TITLE
New F&E start page with guidance

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#456]
Implement the new start page as outlined in the attached document and mocked at https://find-npd-data.herokuapp.com/new-start

[FandE Start Page.docx](https://github.com/DFE-Digital/npd-find-and-explore/files/3897028/FandE.Start.Page.docx)

**Comment by RICHARDMACHEN1** [comment]
**Prototype**

![Start Page Screenshot](https://user-images.githubusercontent.com/48243847/72968561-aa167a80-3dbb-11ea-8242-2260ce8bbc5c.png)

**Acceptance Criteria**

Given I am on the Start page
When I click the ‘home’ link within the breadcrumbs
Then I am taken Department for Education home page on GOV.uk (link -  https://www.gov.uk/government/organisations/department-for-education)

Given I am on the Start page
When I click the ‘Education, Training and Skills’ within the breadcrumbs
Then I am taken Education, Training and Skills page on GOV.uk (link - ‘Education, Training and Skills’ link - https://www.gov.uk/education)

Given I am on the Start page
When I click the ‘GOV.UK’ text in the banner at the top of the Start page
Then I am taken GOV.UK home page (link - https://www.gov.uk/)

Given I am on the Start page
When I click the ‘Department for Education’ link near the top of the Start page 
Then I am taken Department for Education home page on GOV.uk (link -  https://www.gov.uk/government/organisations/department-for-education)

Given I am on the Start page
When I click on the green ‘Start’ button
Then I am taken to the 'Find and explore data in the National Pupil Database' home page (link - https://s112p01-find-npd-data.azurewebsites.net/)

Given I am on the Start page
When I click the ‘Education, Training and Skills’ link near the bottom of the Start page 
Then I am taken Education, Training and Skills page on GOV.uk (link - ‘Education, Training and Skills’ link - https://www.gov.uk/education)

**Comment by RICHARDMACHEN1** [comment]
Sorry, can we change the title please - see attachment
![Start Page Title](https://user-images.githubusercontent.com/48243847/73273255-987a0c00-41db-11ea-967c-814862575ec4.PNG)
My fault :-(
