### ISSUE TITLE
Check \ edit \ delete categories

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#46]
### An epic that covers a user editing a category. 

**As an** NPD team member
**I [need/want]** to be able to edit the category tree 
**So that** it remains acurate to how we believe users can find information intuitively

The following functionality has been created in Rails Admin, but we want to talk around this to make sure we havent missed a better way to deliver the best solution.

1. View a list of all categories
2. Edit categories
3. Re-order\restrcuture categories
4. Add a data item to a concept
5. View a list of all concepts
6. Create a new category
7. Add a concept to a category

### Scenarios

**Given** [some setup, as a type of user]
**When** [I carry out some action]
**Then** [I expect something to happen]

**Comment by benmemmott** [comment]
Linked heavily to 45. Need to think around workflow.

**Comment by krios82** [comment]
Fix current bugs
Make data elements readonly
