### ISSUE TITLE
My List Update – output CSV file with data item and year requirements

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#480]
### Enables a user output their saved data items and requisite meta-data to a CSV file along with the years required for each item 

**As a** an F&E user
**I want** be able to access my data items as a CSV file (with the time frames required) 
**in order to** copy this into an application form and be sure I have given the DFE all the information they need to process my request

### Scenarios

1. Successful completion
**Given** I have saved four data items <KS2_EXAMYEAR_EN, KS2_EXAMYEAR_RE, EVERFSM_6_[term][yy] and HomeLA_[term][yy]>
**And** I have clicked the ‘View My List’’ button
**And** I have filled in the years required for all four data items
**When** I click the ‘’Export to CSV file’’ button
**Then** my browser saves a CSV file with my data items contained.

2. Years required not completed
**Given** I have saved four data items <KS2_EXAMYEAR_EN, KS2_EXAMYEAR_RE, EVERFSM_6_[term][yy] and HomeLA_[term][yy]>
**And** I have clicked the ‘View My List’’ button
**And** I have not filled any of the years required for all four data items
**When** I click the ‘’Export to CSV file’’ button
**Then** a warning is displayed that ‘’All ‘years required’ fields must be completed’’ {copy?} .

Note 1: Data items in the CSV should be in the same order as they appeared on the ‘’My List’’ - ie in dataset subsets
Note 2: Drop down boxes should only allow years that are available for that item
Note 3: An entry with the same year in each box equates to requiring one year of data
Note 4: As per scenario 2, system should mandate a selected value for ‘From’ and ‘To’ for each data item
Note 5: System should not allow a reverse range - for example '2011 to 2006''. (can speak about the error handling when you code it).

![My List Enhanced CSV Output 2](https://user-images.githubusercontent.com/48209167/72255426-9a01dc80-35fe-11ea-9009-ac228caf8396.PNG)

**Comment by krios82** [comment]
Don't allow reverse dates -> preferred version disable the unavailable options.
Also add backend validation & error message.
