### ISSUE TITLE
Bug – ID and Sensitivity modal boxes not displaying correctly

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#490]
### When a user hovers their cursor over either of the 'i' modals on a concept or dataset page, the box is not displayed correctly

**Steps to reproduce
1. On staging go to any dataset or any concept
2. Hover cursor over either 'i' modals for ID or sensitivity
3. See that you cant read the box - it appears to be partially hidden

Note 1: Only seems to happen in Chrome on staging

**Comment by RICHARDMACHEN1** [comment]
Tested but still happening for the modal on the left hand side. Moved back to 'to do'. Cheers
