### ISSUE TITLE
Bug – reference to 'Data Items'

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#494]
### we should be calling them 'data elements'

Places I can find 'item' so far:
1. Red box warning on concept pages
2. Main paragraph of 'My List'
3. ''You can use the checkboxes below to save any items you may want to add to your application'' on concept pages and dataset pages

**Comment by RICHARDMACHEN1** [comment]
Checked:

1. Red box warning on concept pages
2. Main paragraph of 'My List'
3. ''You can use the checkboxes below to save any items you may want to add to your application'' on concept pages and dataset pages

No reference to data items in these areas.
