### ISSUE TITLE
Bug – Delete word 'Variables' in Concept and Dataset pages

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#495]
The word 'Variables' appears on Concept and Dataset pages. Can we delete this and move the 'Save to my list' button up along with the rest of the page.

**Comment by benmemmott** [comment]
Very rough UX below (there's too much space in the middle between 2017 and Save to my list). Could possibly try making 'Data elements' a slightly larger size. 

![variables ux](https://user-images.githubusercontent.com/48209167/72796662-a0640a00-3c37-11ea-9c8f-a7b4ab2cfabf.PNG)

**Comment by RICHARDMACHEN1** [comment]
I have checked several Concept & Dataset pages & can't see any references to 'variables'
