### ISSUE TITLE
My List – System remembers years and notes input if user moves away from page

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#496]
### If a user inputs years required or notes on the My list page, then clicks back into the system, then goes bac, the years and\or notes should be remembered so they don't have to resubmit

**As a** F&E user
**I [need/want]** the system to remember what dates and notes I've requested on the My List page in the event of me clicking away from that page
**in order to** save me repeating my actions

### Scenarios

**Given** I have added <CIN_At31> to My List
**And** I have selected dates 2017-18 to 2018-19
**And** I have entered ''I think'' into the notes box
**And** I have then clicked to view the CIN dataset
**When** I select My List again
**Then** I see <CIN_At31> data element
**And** the years option still populated
**And** the note box still populated

Note 1: These can be forgotten once the session has expired

**Comment by RICHARDMACHEN1** [comment]
Tested & looks fine to me.
