### ISSUE TITLE
Bug – unusual characters on IA and DT causing search issues

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#501]
### unusual characters causing searches to fail

With the example of 'Local Authority Code' where the spaces are not spaces (character type 160). 

Solution could be to convert any space-like character into a true space character during ingestion

**Comment by RICHARDMACHEN1** [comment]
Front End: I searched 'phone' and expected to see something in the search about pupil's phone numbers. It came up second on the list after 'phonics'. That is fine IMO. I then searched LA Code & it returned things I would expect to see. I then searched other things like IDACI & it returned the search as expected.

Back End: I did the same searches & it looked fine.

I'm happy to sign this off. are you @benmemmott
