### ISSUE TITLE
Search results page – results

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#51]
### Allows user to see results returned from their search term

**As a** researcher
**I want** to see name, description and category for each result after i have submitted a search term 
**in order to** understand if i want to explore that result further

### Scenarios

1. Presented results
**Given** I have entered 'FSM' as a search term
**When** I have clicked 'Search'
**Then** I am presented with a page of results
**And** for each result i see a concept name, concept description and category name

2. Links to results 
**Given** I am on a populated search results page for 'FSM'
**When** I click on the title of the 'FSM past 6 years' result
**Then** I am taken to the 'FSM past 6 years' detail page

**Comment by benmemmott** [comment]
![51](https://user-images.githubusercontent.com/48209167/54425878-586a8180-470e-11e9-9c99-0a7af184110a.JPG)

**Comment by krios82** [comment]
Tackled along with https://github.com/DFE-Digital/npd-find-and-explore/issues/49 in https://github.com/DFE-Digital/npd-find-and-explore/pull/77
