### ISSUE TITLE
Search query – 'Postcode'

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#539]
### We've found this scenario and we just want to query if the logic is working correctly

1. Enter 'Postcode' into search
2. Brings back 47 results
3. 'Mobility indicator' comes out first
4. 'Pupil postcode' comes out 22nd

We had a look at where 'Postcode' appeared on those concept pages.

In 'Mobility indicator' it appeared:
- Once in concept description
- Once in the data element description

In 'Pupil postcode' it appeared:
- Once in concept name
- Twice in concept description
- 11 times in data element names
- 9 times in data element descriptions

In the admin docs it states that search is scored on these areas, with the order denoting weighting:
•	concept name
•	concept description
•	data elements: source table name + source attribute name
•	data elements: npd alias + description + old attribute name + data type

I'm not very good at this sort of logic, but I reckon going on the first two lines of that list, 'Pupil postcode' should come higher. Sorry, I know the search is a pain, and you may not get time to look at it, we just thought this was a good example.

**Comment by krios82** [comment]
We can definitely improve the search, but it will require a fair amount of work and research.

First thing, I think the relevance of each result for the search is also weighted as a percentage on how often the search "key" (in this case the word "postcode") appears overall in the whole list of *all* the search keys extracted for the concept.

In this specific example I think the main problem in "Pupil postcode" is that there's a load of rather different data elements (which generates a load of different search keys) and specifically the occurrences of "postcode" are almost never full words: in the element descriptions there's often the "post code" (space in between, two distinct words) or the npd_alias (scored very low anyway) _contain_ postcode (like "PRU_Postcode_SPR"), but it's almost never the full word and just the full word.

These are easily recognisable as the same word from a human perspective, but computers aren't very good at that sort of things.

So effectively in "Pupil postcode", the occurrences are:
* once in concept name
* twice in concept description (but I'm not 100% sure if the /postcode/ part is recognised as a separate word or not, it may be just once in concept description)
* 0 times in data element *npd alias* (not source table name)
* 10 times in data element source table name
* 4 times in data element description

For "Mobility indicator", instead, there's less occurrences, but also less words overall, so the weight of the "postcode" key is higher in "Mobility indicator".

**Comment by dgamblin3008** [comment]
Closing this as the changes were applied under ticket #644
