### ISSUE TITLE
Search – improvement spike

### ISSUE THREAD

**Issue by benmemmott** [DFE-Digital/npd-find-and-explore#546]
Some work to review how search could be improved. We suspect that the poor quality of descriptions in the data elements have made search results more erratic, but it would be worth investigating if another type of search could be implemented- the one used is standard, and we've tinkered with it to improve it but the whole area needs a dedicated period of review.
- Tech Resource to review current code
- TR to advise if improvements can be to the existing code
- TR to investigate if another search engine would be better

**Comment by dgamblin3008** [comment]
Dave Gamblin and Cristina Acquani to have a discussion around this on 03/09/2020

**Comment by dgamblin3008** [comment]
Closing this as the changes were applied under ticket #644
