### ISSUE TITLE
Ingest data from Excel Data Tables

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#56]
In order to develop the system against "real" data
I want to be able to load the Excel Data Tables file into the service

Some thoughts:
- Manually specifying blocks is probably fine for the first pass (unless automatic selection of tables within worksheets is straightforward...)
- We don't need to a web UI, this can be loaded as a rake task or some other developer tool
- We don't need to worry too much about validations, which can be covered under the user-facing admin tasks (#46)
- We can ignore codeset loading (for now) and cover that in #38.

**Comment by krios82** [comment]
**PR #57:**

* Bring in and clean up a bit the script from from https://github.com/DFE-Digital/DfE_data_tables_excel_parser
* Add scripts to parse the Category Tree document

**TO DO:**

* Clean up the code further
* Expand Category Tree parsing to match `Category` with `DataElement` (through `Concept` ?)
* Add specs

**Comment by spikeheap** [comment]
Hi @cacquani, do you have some notes on how to run this ingestion, or a rake task wrapper for it?
