### ISSUE TITLE
Duplicate ID’s Issue

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#597]
# Automated Testing General Findings

## Duplicate ID’s Issue

Your service has multiple instances of duplicate IDs. Without correcting these issues user agents, including assistive technologies, may not be able to accurately interpret and parse content. If the content cannot be parsed into a data structure, then different user agents may present it differently or be completely unable to parse it. 

Success Criterion 4.1.1 Parsing (Level A): In content implemented using mark-up languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features.

*Page links:* https://find-npd-data.education.gov.uk/en/datasets/360866cc-d29e-4df8-9f93-fdb9f8e801b9

## Actions:

Since the page link in the accessibility statement isn't a link to our service, the first required action for this ticket is to go through our service and verify if there's actually any instance of duplicated IDs on our service.

Once the investigation is done, any duplicated ID should be corrected and made unique.

**Comment by dgamblin3008** [comment]
Updated the link in the description section after speaking with Nick Jarvis-Smith, who wrote the report.
He also gave an example of the HTML text that is repeated as 'sensitivity-tip-before'.
@cacquani do you know what he means by this?

**Comment by dgamblin3008** [comment]
@cacquani after running through this with you yesterday on staging, I'm happy that the work's been done and I've tested it.

**Comment by dgamblin3008** [comment]
Awaiting the result of the accessibility test on 14/09/2020.

**Comment by dgamblin3008** [comment]
The accessibility re-test picked up no issues, so this change is ready to push to production.

**Comment by dgamblin3008** [comment]
PO has agreed to close the ticket.
