### ISSUE TITLE
Dev spike - Investigate aligning data elements column header text  

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#612]
**ISSUES**
On pages showing lists of data elements - i.e Datasets pages, Concepts pages, the 'My list' page - there are two issues:

1. The column header text for 'Sensitivity' and 'Identifiability' is slightly misaligned with the rest of the column headers.  
2. The final column, 'Values' needs to be widened so the words 'Codeset' and 'Alphanumeric' don't wrap over two lines.

**Comment by krios82** [comment]
Suggested changes:

1. Change the css rules for the tooltip as follow:
    * font size from "19px" to "16px"
    * margin-left from "8px" to "2px"
    * padding from "3px 12px 0" to "1px 8px 0"
    <img width="996" alt="Screen Shot 2020-09-18 at 12 44 43" src="https://user-images.githubusercontent.com/2742327/93593878-c13e5400-f9ac-11ea-8b71-c4701ac3336b.png">


---
2. For the final column, change the css rule for that column to "word-break: keep-all;", so that it will not break a word in half. 
    <img width="761" alt="Screen Shot 2020-09-18 at 12 46 18" src="https://user-images.githubusercontent.com/2742327/93594018-fc408780-f9ac-11ea-8a9e-e6168d90ecde.png">

**Comment by dgamblin3008** [comment]
@cacquani that looks good. A couple of minor things:

1. Could we make the 'i' icons just slightly smaller?
2. Could you show me how it looks on the 'My list' page?

Thanks
Dave

**Comment by krios82** [comment]
New screenshot of the 'My List' page after making the 'i' icon smaller:

<img width="933" alt="Screen Shot 2020-09-23 at 12 05 57" src="https://user-images.githubusercontent.com/2742327/94017096-ea912280-fda6-11ea-9c79-b00c778468a3.png">

**Comment by dgamblin3008** [comment]
Ticket moved to 'Done' and closed. Ticket #617 raised to implement the changes.
