### ISSUE TITLE
Changes to layout of Data Elements tables

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#617]
**INFO**
1. This ticket follows on from dev spike #612 
2. The changes apply wherever a Data Elements table is displayed - i.e. all Datasets pages, Concepts pages, My list.

**ACCEPTANCE CRITERIA**
The required changes are shown in the following screenshot: 
<img width="952" alt="Data Elements table changes 25-09-2020" src="https://user-images.githubusercontent.com/66372153/94245349-036a1700-ff12-11ea-883f-be501768bda3.png">

The changes apply to all Dataset pages, Concepts pages and My list pages, unless stated otherwise, and are
1.  Column header text should be top aligned.
2. The 'i' icons should be reduced in size and appear centrally under the column header text 'Sensitivity' and 'Identifiability'.
3. The 'Name' column should be extended to the left, so there is less white space between it and the checkboxes - NB this change does not apply to the My list page, which does not have checkboxes.
4. The 'Values' column should be able to accommodate the word 'Alphanumeric' without it wrapping to the next line.  
5. The checkboxes should be top aligned, so the top of the checkboxes are in line with the top of the text in each column.

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
We also agreed that the checkboxes should be top aligned so that if there are any data elements that are lucky enough to be on a single line then the amount of space in that row is reduced thereby increasing the number of data elements on one page.

**Comment by dgamblin3008** [comment]
Alignment of checkboxes added. Assigning to @cacquani to action.

**Comment by dgamblin3008** [comment]
tested and successfully released to production on 07/10/2020. Ticket closed.
