### ISSUE TITLE
Reduce white space on My list page

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#618]
**INFO**
There is large area of white space at the top of the My list page, above the green 'Export...' buttons. To make the My list page a better user experience, this white space should be reduced.

**ACCEPTANCE CRITERIA**
1. The 'My list' header text should be moved downwards, so that the top of the 'My list' text is aligned with the top of the blue box that contains the 'Save in this session' text.
![My list white space](https://user-images.githubusercontent.com/66372153/94249668-1e3f8a00-ff18-11ea-86ca-5b72f2498e31.PNG)

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Assigning to @cacquani to action

**Comment by dgamblin3008** [comment]
Tested and released to production on 07/10/2020. Ticket closed.
