### ISSUE TITLE
Migrate dataset/tab matching markers from hardcoded into database

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#621]
# Reasons for implementation

The current version of the F&E tool is hardcoded to only consider a fixed subset of NPD datasets.

The real scope of the tool is wider, and the admin users should have the ability to import datasets that are not currently included in the fixed subset of imported NPD datasets.

To allow that, we need to remove the hardcoded logic and make the system more flexible.

# Details

* Add the database structure needed to support the new implementation
* Migrate the currently hardcoded markers from code into the database
* Change the code to use the new markers from database

**Comment by dgamblin3008** [comment]
@cacquani Looks good, thanks. I just tinkered with the wording slightly.
Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
Just replaced the word "should be much wider" to "is much wider".  Otherwise approved

**Comment by dgamblin3008** [comment]
Ticket is approved, so removing Gwen McGill from list of assignees

**Comment by dgamblin3008** [comment]
This functionality has been released to production. so ticket can be closed.
