### ISSUE TITLE
Expand unique identifier logic to use other than NPD Alias

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#622]
# Reasons for development

The **NPD Alias** field was originally flagged as a unique identifier for a data element, but this is only true for NPD datasets.

Other datasets use different unique identifiers, for instance the SLD tables use **SLD Alias**, and further down the line more datasets will be added that will use new unique identifiers.

# Details

* Add the additional database fields needed to remember what is the **unique id name** for a specific dataset
* Change the code to use the additional field to recognise the unique ID when importing a data table
* Change the code to use as unique ID the pair **unique ID name**/**unique ID value**

**Comment by dgamblin3008** [comment]
@cacquani looks good. Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
Approved.

**Comment by dgamblin3008** [comment]
Ticket is approved, so removing Gwen McGill form list of assignees.

**Comment by dgamblin3008** [comment]
This functionality has been released to production, so ticket can be closed.
