### ISSUE TITLE
Bug - Admin Area: Update 'Change password' tooltip

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#628]
# Issue

In the admin area, when trying to change a password, the tooltip is outdated.

It still says minimum 6 characters, when the new requirements are minimum 8 characters, of which at least one uppercase letter, one lowercase letter, one special character and one number.

# Fix

Change the tooltip to reflect the actual password requisites.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested  by trying to change to an admin password that was too short, didn't contain the necessary characters and using a password confirmation that didn't match. All three errors were picked up and the correct error message shown.

**Comment by dgamblin3008** [comment]
Will ask users to do UAT.

**Comment by dgamblin3008** [comment]
Passed UAT on staging 3/11/2020.
Tested successfully on live 6/11/2020.
