### ISSUE TITLE
Bug - Admin Area: Can't assign new data elements to concepts 

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#629]
# Issue

When editing a concept to add new data elements, some of the data elements (especially if newly added to the system) don't show up in the search box.

# Fix

The data elements needs to be searched by dataset + NPD alias, not by NPD alias alone. When searching for NPD alias alone it will not show up in the search.

Change the search so that it will also find the element when searching for NPD alias alone.

**Comment by GMcGill-DfE** [comment]
Approved.  Although please note that this bug fix will need to be included in the impact of "removing the hard-coding / configuration" work.  For example, searching by NPD alias will not find SLD data elements.

**Comment by dgamblin3008** [comment]
Tested on staging. Will get users to UAT it.

**Comment by dgamblin3008** [comment]
Passed UAT on staging 3/11/2020.
Tested successfully on live 6/11/2020.
