### ISSUE TITLE
Improve performance of Data Tables loader

### ISSUE THREAD

**Issue by spikeheap** [DFE-Digital/npd-find-and-explore#63]
Loading the Data Tables file takes >60 minutes on my 2013 MacBook Pro. When we get onto #45 and build a UI for the Data Tables to be loaded this is likely to be prohibitive, so this issue is a placeholder for investigating potential performance improvements prior to that.

Ideally our perf goal is <10 seconds, so we can keep the user in a single flow (sub-second would be amazing, but getting there from 60 minutes feels like a bit of an ask). If we go above this we may need to consider async messaging with notifications once the load is complete.

**Comment by krios82** [comment]
Also investigate about a bug in the category/concept loading.
Example of failing assignment: IDACI
