### ISSUE TITLE
Admin area: Add total number of items in list pages

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#630]
As an F&E administrator
I want the admin tool to show me how many categories, concepts and data elements are in its paginated lists
So that I can more easily check the outcome of a Data Tables import   

# Issue

In the admin area, there are several paginated lists, but all of them lack the total number of items.

This is not strictly a bug, but it could be useful for the users to have an indication of how many items there are in total in each list.

**Comment by GMcGill-DfE** [comment]
I would like this requirement to include the "so what?" aspect of the user story.  "As a user I want to be able to see the total number of items [in each list] in order to [do what?]."  I will want to review again once revised.

**Comment by dgamblin3008** [comment]
@GMcGill-DfE - I've added a user story for this. Assigning it to you to review.

**Comment by GMcGill-DfE** [comment]
Thats great thanks.  Approved.

**Comment by dgamblin3008** [comment]
@cacquani ticket is now approved so can be actioned. Thanks.

**Comment by dgamblin3008** [comment]
Tested. Will get users to do UAT.

**Comment by dgamblin3008** [comment]
Passed UAT on staging 3/11/2020.
Tested successfully on live 6/11/2020.
