### ISSUE TITLE
Bug - Admin Area: Can't add or move subcategories using the 'Sort Categories' tool

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#631]
# Issue

When signed in as an admin user, the 'Sort Categories' tool doesn't let you add a subcategory to a category that doesn't already have any subcategories.

# Fix

Tweak the sorting functionality so that it will be able to drag a category into another and make it a subcategory.

**Comment by GMcGill-DfE** [comment]
Approved.

**Comment by dgamblin3008** [comment]
Tested. Will get users to UAT.

**Comment by dgamblin3008** [comment]
Passed UAT on staging 3/11/2020.
Tested successfully on live 6/11/2020.
