### ISSUE TITLE
Limit 'Values' column to 30 characters

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#640]
On pages that display data elements, i.e. Dataset pages, Concept pages and 'My list' pages, then the 'Values' column should display text only up to 30 characters.

Where the 'Values' text is more than 30 characters, there should be a link called 'Allowed values' that displays the text as an overlay.  The 'Allowed values' link should replace the current 'Codesets' link.

**Comment by dgamblin3008** [comment]
Assigned to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
"codeset" can only apply to a list of values that is a pick list.  It cannot be used to describe a lengthy description of a value format.  For that you could use something like "More info"

**Comment by dgamblin3008** [comment]
It isn't possible to automatically differentiate between a list of values and a description of value format. So we can't use both 'Codeset' and 'More info' links. In the NPD Data Tables, all of these values come under the heading 'Allowed values'. Renaming the  'Codeset' link 'Allowed values' would therefore meet the requirement.
Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested by choosing 8 different datasets at random - checked that all links said 'Allowed values' and that they worked; checked that none of the values shown directly in the column exceeded 30 characters. All tests passed.
Ready for UAT.

**Comment by dgamblin3008** [comment]
UAT was carried out on 3/11/2020, there were no issues. 
Tested in live on 6/11/2020 - there were no issues so moving to done and closing the ticket.
