### ISSUE TITLE
Implement improved search functionality

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#644]
This ticket follows on from spikes #600 and #601. 

**User story**
As an education researcher
I want to search for specific NPD data items
So that I can use the data in my research

**Acceptance criteria**
1. The search will look through data elements as follows - unique alias, human readable name, description and old name.
2. The search will look for an exact match, and if there isn't an exact match, will search for partial matches.
3. Data elements in the search return list can be added to 'My list'.
4. Each data element name in the search return list will be a link that takes a user to its single data item page.  
5. The current filtering functionality is unchanged, although the 'Categories' filter will be renamed 'Concepts', and the order of the filters on the page will be 'Datasets', 'Years', 'Concepts' from top to bottom.
6. The search return page layout should be redesigned as shwon in the UED below.

**UED**
[Data elements search results V4.pdf](https://github.com/DFE-Digital/npd-find-and-explore/files/5590642/Data.elements.search.results.V4.pdf)

**Comment by GMcGill-DfE** [comment]
Do you need to mention the filters in the LHS navigation pane or is this working as we expect and will be there as we expect?  If no need to mention LHS navigation pane for filtering results then happy to approve.

**Comment by GMcGill-DfE** [comment]
Apologies, closed by mistake.

**Comment by dgamblin3008** [comment]
@GMcGill-DfE I think the filters are fine. It's probably worth mentioning that, though - I'll add it to the acceptance criteria.

**Comment by GMcGill-DfE** [comment]
Ok cool

**Comment by dgamblin3008** [comment]
Assigning to @cacquani

**Comment by dgamblin3008** [comment]
@cacquani the final, approved UED is now attached.

**Comment by dgamblin3008** [comment]
Tested and passed. Will get users to do UAT.

**Comment by dgamblin3008** [comment]
Passed UAT and released to production. Post release checks passed. Ticket closed.
