### ISSUE TITLE
Remove prefix from data element names and make all data element names links  

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#660]
### User stories

**As an** education researcher
**I want** data element names in NPD F&E to be displayed in the same format as those in the NPD Data Tables 
**So that** the data element names are displayed consistently 

**As an** education researcher
**I want** each data element name in NPD F&E to be a link to further information about the data element
**So that** I don't have to search around for the information

### Acceptance criteria

1. On all pages, data element names should not have an added prefix to identify the dataset, e.g. 'Absence.AcademicYear_ab[yy]' should be shown as 'AcademicYear_ab[yy]'.
2. On all pages, each data element name should be a hyperlink that take the user to the new single data element page.

**Comment by dgamblin3008** [comment]
@GMcGill-DfE assigning to you for approval. These are changes that were agreed in last Thursday's 'admin pages' and 'search function' workshops, but are separate pieces of work.

**Comment by GMcGill-DfE** [comment]
Approved.  Thanks

**Comment by dgamblin3008** [comment]
Closed in error. Reopened.

**Comment by dgamblin3008** [comment]
Assigning to @cacquani

**Comment by GMcGill-DfE** [comment]
Sorry!! Thanks Dave!

**Comment by dgamblin3008** [comment]
Tested and passed. Will get users to do UAT.

**Comment by dgamblin3008** [comment]
Passed UAT and released to production. Post release checks passed. Ticket closed.
