### ISSUE TITLE
Amend 'Start' page text and rename 'Data elements' throughout website

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#667]
**1. On the F&E 'Start' page, the following text changes should be made:**

i. Change the text directly below the page header text from

'Use this tool to find and explore data in the NPD, a key DfE data store, covering education, skills and children services data for individual learners in England, before [applying to access](https://www.gov.uk/guidance/how-to-access-department-for-education-dfe-data-extracts) Department for Education (DfE) data extracts.'

to

'Use this tool to find and explore information about the data that is held in the NPD, a key DfE data store, covering education, skills and children services data for individual learners in England, before [applying to access](https://www.gov.uk/guidance/how-to-access-department-for-education-dfe-data-extracts) Department for Education (DfE) data extracts.'

ii. Change the text in the '**Searching for data**' section from 

'You can also find specific categories using a simple text search.'

to

'You can also find specific data items using a simple text search.'

**2. On all F&E Dataset pages and all Concept pages change the text above the list from** 

'You can use the checkboxes below to add data elements to your list'

to

'You can use the checkboxes below to add data items to My List.'

**3. On all pages where the access to 'My list' button appears** 
![image](https://user-images.githubusercontent.com/66372153/100904502-fdb72180-34be-11eb-9167-5f800d484e34.png)

change the text in the box from '**My list**' to '**View My List**'

**4. On the 'My List' page**

i. Change the page title header from '**My list**' to '**My List**'

ii. Change the text directly under the title header from

'You can export this list of data elements into a .xlsx or .ods file.'

to

'You can export this list of data items into a .xlsx or .ods file.'

iii. Change the text in the blue box from

'This list of data elements will disappear when you clear your cookies for this site or by selecting 'Remove all' below.'

to

'This list of data items will disappear if you clear your cookies for this site or by selecting 'Remove all' below.'

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE fpr approval.

**Comment by GMcGill-DfE** [comment]
'You can export this list of data item into a .xlsx or .ods file.'  should be 'You can export this list of data items into a .xlsx or .ods file.'

Basically, make sure "data items" is plural.

**Comment by GMcGill-DfE** [comment]
Otherwise fine.

**Comment by dgamblin3008** [comment]
Good spot.  Have a good evening.

**Comment by GMcGill-DfE** [comment]
Thanks

**Comment by dgamblin3008** [comment]
Assigning to @cacquani to action.

**Comment by dgamblin3008** [comment]
Released to live and successfully tested.
