### ISSUE TITLE
Amend landing page text 

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#668]
**User story**
As an education researcher
I want to know what information the F&E 'search', datasets' and 'categories' sections provide
So that I can quickly find the data I want

**Acceptance criteria**
1. On the page showing 'Search', 'Datasets' and 'Categories', Insert the following explanatory text:

'Use this tool to find and explore information about the data that is held in the NPD, before applying to access Department for Education (DfE) data extracts. You can search for specific data items, browse through the data items in each dataset (the data collections that feed into the NPD) or browse down via high level data categories until you find the group of data items you’re interested in. You can add data items to My List.'

2. The text should be inserted below the header, here:

![image](https://user-images.githubusercontent.com/66372153/101023231-61e2ef80-356a-11eb-884c-853af5b319e7.png)

3. The text 'applying  to access' should be a hyperlink to https://www.gov.uk/guidance/how-to-access-department-for-education-dfe-data-extracts

**Comment by dgamblin3008** [comment]
Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
looks good to me

**Comment by dgamblin3008** [comment]
@cacquani this ticket has been approved so can be picked up when you have time. Thanks.

**Comment by dgamblin3008** [comment]
Released to live and successfully tested.
