### ISSUE TITLE
Remove Staging environment from Google Analytics

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#670]
**User story**
As F&E Product Owner
I want to see analytical data for the Production environment only
So that I can analyse activity for external F&E users

**Info**
1. Currently, Google Analytics data includes both the Staging and Production environments.
2. The Staging environment should be removed from GA, so that GA data is for the Production environment only.

**Comment by dgamblin3008** [comment]
Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
approved

**Comment by dgamblin3008** [comment]
@cacquani ticket to be picked up when you have time.

**Comment by dgamblin3008** [comment]
Released to production.
