### ISSUE TITLE
Replace option to download NPD Data Tables on Concept pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#671]
**User story**
As an education researcher
I want to be able to email a request for further information on Find & Explore
So that I can find the data I want

**Acceptance criteria**
1. At the bottom of each Concept page, the following hyperlink should be removed:
'Can't find what you're looking for? [Click here to download the latest version of the NPD Data Tables](https://forms.gle/okheDrnUL224Dusm9)'
2. It should be replaced with an option for the user to make an email request for further information, so that it reads:
''Can't find what you're looking for? Contact data.sharing@education.gov.uk'
3. Clicking on 'data.sharing@education.gov.uk' should generate an email message to 'data.sharing@education.go.uk' with the title 'Find & Explore query' in the subject field.
4. The body of the email message should be blank for the user to enter details of their query.
5. The 'Download NPD Data Tables file' page that currently is reached after requesting the latest version of the NPD Data Tables should be removed, in case any users have it bookmarked.

**Comment by dgamblin3008** [comment]
Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
approved

**Comment by dgamblin3008** [comment]
@cacquani - to be actioned when you have the time.

**Comment by dgamblin3008** [comment]
Released to live and successfully tested.
