### ISSUE TITLE
Admin area: redesign 'Sort Categories' function

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#676]
**User story**
As an F&E admin user
I want to reorganise the Categories and Concepts structure
So that changes to NPD data can be applied to F&E

**UEDs**
![Categories V5a](https://user-images.githubusercontent.com/66372153/102520487-a94d9d80-408b-11eb-91bf-9b7474916abd.png)
![Categories V5b](https://user-images.githubusercontent.com/66372153/102520517-b10d4200-408b-11eb-8328-8a67c892659a.png)

**Acceptance criteria**
New 'Sort Categories and Concepts' structure to be developed as per the UED above. Additional info: 
1. Remove the existing 'Categories' table.
2. Remove the existing 'Concepts' table.
3. Rename 'Sort Categories' to 'Sort Categories and Concepts'. 
4. Restyle the 'Sort Categories and Concepts' page to add a new right hand menu as in the UED
    - in the 'Filters' section, unticking either of the options collapses the categories or concepts;
    - whether the filters are checked are unchecked, users can manually expand or collapse individual categories and concepts, 
    - the 'Change log' displays a list of the drag and drop actions that have been made, but the actions aren't permanently applied 'Changes have been approved' is checked and the 'Confirm' button is clicked;
    - clicking the 'Cancel' button clears the change log and returns the categories and concepts to the state prior to the actions listed in the change log.
5. Add additional elements to the horizontal Categories bars
    - the number of 'children' (categories, concepts) 
    - An 'Edit' link - clicking the 'Edit' link allows the user to change the name and description of the category, and allows the user to delete the category. If 'delete is selected, a warning should be issued that the category will be permanently deleted, with an option to continue or cancel; when a category is deleted, it's sub-categories and concepts will go into the 'No category' container (NB this is the current functionality, so no change);
    - a 'View detail' link, to show description and additional data.
6. Add horizontal Concepts bars that show
    - the name of the concept;
    - the number 'children' (data items)
    - An 'Edit' link -clicking the 'Edit' link allows the user to change the name and description of the concept, and allows the user to delete the concept. If 'delete is selected, a warning should be issued that the concept will be permanently deleted, with an option to continue or cancel; when a concept is deleted, it's data items will co into the 'Orphaned Data Items' container (NB this is the current functionality, so no change);   
    - A 'View detail' link, to show description and additional data
7. Add functionality to 'expand' and 'collapse' the categories and concepts.

**Comment by GMcGill-DfE** [comment]
OMG. Brain fried.  I am going to assume your acceptance criteria is correct. 

Approved.

**Comment by dgamblin3008** [comment]
Released to live and successfully tested on 8 January 2021.
