### ISSUE TITLE
Admin Area: allow admin users to delete datasets

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#679]
**As a** F&E admin user
**I want** the ability to delete datasets 
**So that** F&E users don't see redundant datasets 

### Scenarios
**Given** I've logged in to F&E as an admin user
**When** I view the list of datasets
**Then** there is an option to delete each dataset

### Acceptance Criteria
1. When clicking delete, the user is asked to confirm that they wish to delete the dataset. 
2. When a dataset is deleted, its data items are deleted.
3. Where a data item belongs to more than one dataset and one of the datasets is deleted, the data item stays in the undeleted dataset.

**Comment by dgamblin3008** [comment]
@GMcGill-DfE assigning this to you to approve.  Currently, there is no way of deleting datasets from F&E - after speaking with Martin and Janet, they feel this is a requirement, although it will only ever rarely be used.

**Comment by GMcGill-DfE** [comment]
I'm pretty sure I asked for this at one of the workshops to give us maximum flexibility over managing the site so yes definitely approve.  However, can you double check the acceptance criteria with Martin and Janet please.

**Comment by dgamblin3008** [comment]
Checked with Martin and Janet and they've agreed the ACs.
@cacquani to pick up when you have time. Thanks.

**Comment by dgamblin3008** [comment]
Passed UAT, can be released to production on 18/12/2020.

**Comment by dgamblin3008** [comment]
Released to live on 18/12/2020.
