### ISSUE TITLE
Admin Area: Add re-index function

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#681]
### User story
**As a** F&E admin user
**I want** the ability to re-index the F&E database  
**So that** the search function works as it should

### Scenarios
**Given** I have logged in to F&E as an admin user
**Then** I have the option to re-index the F&E database

### Info
Sometimes, after a release to production, the F&E search function no longer works. This is an intermittent error that is fixed by re-indexing the database. Re-importing the NPD data tables will trigger a re-index, but it would be easier for an admin user to have a specific re-index option. 

### Acceptance Criteria
1. An option should be added to the admin menu called 'Refresh Search Index'.
2.  When selected, this page will have explanatory text that states - ‘After a new release of Find & Explore to live, the 'Search' function may stop working until the search index is refreshed. Click the button below to start the refresh.’ 
3. The button to initiate the database re-index should be labelled 'Start refresh'.

**Comment by dgamblin3008** [comment]
Assigning to @GMcGill-DfE to approve.

**Comment by GMcGill-DfE** [comment]
User story is fine but we need to add in acceptance criteria for what the text and button is going to say so that it is obvious what action the user is taking.  I don't mind using the word "re-index" but it needs to be clear why the user would press the button.

**Comment by dgamblin3008** [comment]
@GMcGill-DfE yes, this ticket is just really a placeholder so I don't forget, so I shouldn't really have forwarded it for approval. I need to discuss how it's best presented with @cacquani and Mark.

**Comment by dgamblin3008** [comment]
ACs added as agreed with @GMcGill-DfE. Assigning to Gwen to approve the ticket.

**Comment by GMcGill-DfE** [comment]
‘After a new release of Find & Explore to live, the 'Search' function may stop working until the search index is refreshed. Click the button below to start the refresh.’

I'm not sure this text is right given your information text above states "Re-importing the NPD data tables will trigger a re-index".  If the team upload a new or revised data table onto the live admin function this is not the same as releasing a new version of the admin function onto live environment.  Please make either the information text clearer or the second AC.

**Comment by GMcGill-DfE** [comment]
Discussion with Dave Gamblin.  AC text is correct. Approved.

**Comment by dgamblin3008** [comment]
Tested on Staging. Ready or UAT.

**Comment by dgamblin3008** [comment]
Released to live and successfully tested on 8th January 2021.
