### ISSUE TITLE
Admin: fix ordering of categories after IA file import on live environment

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#696]
### Information

- Currently, after an Information Architecture file is imported to the live (production) environment, the top level categories are displayed on F&E in reverse order to how they were displayed when the IA file was created.
- This is a bug and occurs on the live environment only, not on Staging.
- It doesn't appear to be a problem with the IA file itself, because when an IA file is created on live but imported to Staging, it works exactly as it should and the top level categories are displayed in the correct order.

### User Story 

As a F&E admin user
I want the Information Architecture file to reset the top level categories to the order they were in when the IA file was created 
So that I don't have to re-order the top level categories after importing the Information Architecture file  

### Scenarios

Given I have created an Information Architecture file
When I import the file
Then the top level categories are displayed on F&E exactly as they were when the file was created 

### Acceptance Criteria

1. Importing an Information Architecture file resets all categories, concepts and the data items within each concept, to how they were on F&E when the Information Architecture file was created.
2. The order that all categories, concepts and data items are displayed on F&E will be the same as when the Information Architecture was created.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Remove this sentence "This story is added as a placeholder as the work cannot be carried out until an internal developer has been recruited or a contractor employed." Otherwise approved.  No need to send this to me again.

**Comment by dgamblin3008** [comment]
Released to live on 22/06/2021.

**Comment by dgamblin3008** [comment]
Tested on live. Assigning to @GMcGill-DfE for approval to close the ticket.

**Comment by GMcGill-DfE** [comment]
Approved
