### ISSUE TITLE
Admin area: improve overall look and feel and usability of the admin user landing page

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#697]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the Admin tool user page to clear and easy to navigate
So that I can administer Find & Explore effectively

**ACCEPTANCE CRITERIA**
Given I log in to Find & Explore as an admin user
Then I am taken to an Admin Tool landing page as shown in the UED below

**UED**
![0 - NPD Admin landing V2 (variant)](https://user-images.githubusercontent.com/66372153/108742599-c2f9de00-752f-11eb-9a32-3f754c7fdfba.png)

**Business Rules**
1.  The new landing page will replace the current landing page, that has the list of links on the left hand side.
2. The list of links on the left hand side will no longer appear on any page.
3. Navigation will be via a breadcrumb trail at the top left of each page, with the landing page as 'Home'.
4. Clicking the 'Sort categories and concepts' link will take the user to the current 'Sort categories and concepts' page.
5. Clicking the 'Childless categories' link will take the user to a redesigned page, as described in ticket #699 .
6. Clicking the 'Childless concepts' link will take the user to a redesigned page, as described in ticket #700 .  
7. Clicking the 'All data items' link will take the user to a redesigned page, as described in ticket #701 . 
8. Clicking the 'Orphaned data items' link will take the user to the current 'Orphaned data items' page.
9. Clicking the 'All datasets' link will take the user to a redesigned page, as described in ticket #702 .
10. Clicking the 'Recent uploads' link will take the user to a redesigned page, as described in ticket #703 .
11.  Clicking the 'Import data tables' link will take the user to the current 'Import datasets' page (which is currently accessed by clicking 'Import Data Tables' in the list of links on the left hand side of the admin landing page).
12.  Clicking the 'Import categories and concepts backup file' link will take the user to a redesigned page, as described in ticket #704. 
13. . Clicking the 'Create categories and concepts backup file' link will take the user to a redesigned page, as described in ticket #705. 
14. Clicking the 'Manage admin users' link will take the user to a redesigned page, as described in ticket #706. 
15. Clicking the 'Start search index refresh' link will take the user to a redesigned page, as described in ticket #707.

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
I have tested this ticket and everything is good, but will need to re-test when the work to redesign all of the pages that are linked to is complete.

**Comment by dgamblin3008** [comment]
Tested and everything good. Ready for UAT.

**Comment by dgamblin3008** [comment]
Martin Johnson and Janet Crame have carried out UAT and are content that this ticket is done and the changes released to production. 
Gwen McGill has checked the changes on staging and is also content that it can be released to staging.
The ticket will be kept open until the release to production is complete.

**Comment by dgamblin3008** [comment]
Changes released to production and tested. Call closed.
