### ISSUE TITLE
Admin Area: redesign 'Childless categories' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#699]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Childless categories' pages to be clear and easy to use
So that I can assign sub-categories and/or concepts to them 

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Childless categories' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Childless categories' link on the Admin landing page
Then I am taken to the 'Childless categories' page as shown in UED1 

**Scenario 2 - admin user clicks 'View details' link for a childless category**
Given I log in to Find & Explore as an admin user 
And I am on the 'Childless Categories' page
When I click on the 'View details' link
Then the page I see is as shown in UED2 

**Scenario 3 - admin user clicks 'Edit' link for a childless category**
Given I log in to Find & Explore as an admin user 
And I am on the 'Childless Categories' page
When I click on the 'Edit' link
Then the page I see is as shown in UED3

**Scenario 4 - admin user clicks 'Edit category' link on 'View details' page**
Given I log in to Find & Explore as an admin user 
And I am on a childless category's 'View details' page
When I click on the 'Edit category' link
Then the page I see is as shown in UED3

**UED1 - 'Childless categories' page** 
![6 - Childless categories 1 - Landing page](https://user-images.githubusercontent.com/66372153/109040778-33d2fe80-76c6-11eb-8514-e3c86a161f75.png)

**Business Rules for UED1**
1. A full list of childless categories will be displayed here (although the UED shows only one).
2. Clicking 'Home' on the breadcrumb will return the user to the Admin landing page.
2. If there are no childless categories, then the following text will be displayed: 'No childless categories found'.
3. For childless categories, the number of Concepts and Child categories will always be '0'.  

**UED2 - 'View details' page**
![6 - Childless categories 2 - View link followed](https://user-images.githubusercontent.com/66372153/109042106-b60ff280-76c7-11eb-9a1e-dc0b36a3db28.png)

**Business Rules for UED2**
1. Clicking the 'Back' link takes the user back to the 'Childless categories' page.
2. If this category has a parent category or categories, links to their names will be displayed, otherwise it will say 'None'.
3. Clicking on a link to a parent category will take the user to the view details page for that category.
4. 'Child categories' and 'Concepts' will always say 'None'.
5. Clicking 'Edit category' takes the user to Edit page for that category, which is the same page that the user is taken to after clicking 'Edit' on the 'Childless categories' page (see UED3).

**UED3 - 'Edit' page**
![6 - Childless categories 3 - Edit link followed](https://user-images.githubusercontent.com/66372153/109043921-b7dab580-76c9-11eb-8b2e-06d646c8b988.png)

**Business Rules for UED3**
1. Clicking the 'Back' link takes the user back to the 'Childless categories' page.
2. The user can update the category 'Name' and/or 'Description' fields.
3. The user can select concepts to add to the category.
4. Clicking the 'Update category' button updates the category with any changes made on this page and takes the user to the 'View details' page, which shows the updated details for that category.
5. Clicking 'Cancel' takes the user back to the 'View details' page for that category.
6. Clicking the 'Delete category' button takes the user to a page where the user can confirm the delete or cancel it, as shown below.
7. After selecting 'Yes' or 'No' on the 'Delete category?' page, the user is returned to the 'Childless categories' page (UED1).

**'Delete category?' page UED**
![6 - Childess categories 4 - Delete category confirmation](https://user-images.githubusercontent.com/66372153/109046021-333d6680-76cc-11eb-9b47-7888293c5df3.png)

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
@cacquani - just tested an generally it's fine, just one thing - I created a test category and after selecting 'Delete category' on the edit page, then choosing 'No, do not delete <test category>' and clicking 'Confirm', 'I'm returned to the Childless categories page but there's an error message at the top of the page as follows:
![Abort category delete message 31-03-2021](https://user-images.githubusercontent.com/66372153/113121115-36b39880-920a-11eb-9deb-b2e0f491afae.PNG)

**Comment by dgamblin3008** [comment]
Re-tested and everything is good. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
