### ISSUE TITLE
Admin Area: redesign 'Childless concepts' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#700]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Childless concepts' pages to be clear and easy to use
So that I can allocate relevant data items to childless concepts

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Childless concepts' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Childless concepts' link on the Admin landing page
Then I am taken to the 'Childless concepts' page as shown in UED1

**Scenario 2 - admin user clicks 'View details' link for a childless concept**
Given I log in to Find & Explore as an admin user
And I am on the 'Childless Concepts' page
When I click on the 'View details' link
Then the page I see is as shown in UED2

**Scenario 3 - admin user clicks 'Edit' link for a childless concept**
Given I log in to Find & Explore as an admin user
And I am on the 'Childless Concepts' page
When I click on the 'Edit' link
Then the page I see is as shown in UED3

**Scenario 4 - admin user clicks 'Edit concept' link on 'View details' page**
Given I log in to Find & Explore as an admin user
And I am on a childless concept's 'View details' page
When I click on the 'Edit concept' link
Then the page I see is as shown in UED3

**Scenario 5 - admin user clicks 'Category' link on 'View details' page**
Given I log in to Find & Explore as an admin user
And I am on a childless concept's 'View details' page
When I click on the link in the 'Category' field
Then I am taken to the concept's 'Category' page as shown in UED4

**UED1 - 'Childless concepts' page**
![5 - Childless concepts 1 - Landing page](https://user-images.githubusercontent.com/66372153/109334362-86dcbb00-7858-11eb-9a9f-af9ce7eb26dd.png)

**Business Rules for UED1**
1. All childless concepts will be displayed here.
2. Clicking 'Home' on the breadcrumb will return the user to the Admin landing page.
3. If there are no childless concepts, then the following text will be displayed: 'No childless concepts found'.
4. Because these are childless concepts, the number displayed in the 'Data Items' row will always be '0'. 

**UED2 - 'View details' page**
![5 - Childless concepts 2 - Concept View details link followed](https://user-images.githubusercontent.com/66372153/109334623-df13bd00-7858-11eb-980e-455f5edb48c6.png)

**Business Rules for UED2**
1. Clicking the 'Back' link takes the user back to the 'Childless concepts' page.
2. If the concept is in a category, a link to the category will be provided in the 'Category' row. 
3. If the concept is not in a category, the 'Category' row will say 'None'.
4. Because these are childless concepts, the 'Data Items' row will always display 'None'.
5. Clicking on the link in the 'Category' field takes the user to a page for that category, which is shown at UED4.

**UED3 - 'Edit' page**
![5 - Childless concepts 4 - Concept Edit link followed](https://user-images.githubusercontent.com/66372153/109334727-05395d00-7859-11eb-9b5d-32776b52432a.png)

**Business Rules for UED3**
1. Clicking the 'Back' link takes the user back to the 'Childless concepts' page.
2. The user can update the concept 'Name' and/or 'Description' fields.
3. The user can assign the concept to a category using a drop down list in the 'Category' field.  
4. The user can assign data items to the concept using a drop down list in the 'Data Items' field.
5. Clicking the 'Update concept' button updates the concept with any changes made on this page and takes the user to the 'View details' page, which shows the updated details for that concept.
6. Clicking 'Cancel' takes the user back to the 'View details' page for that concept.
7. Clicking the 'Delete concept' button takes the user to a page where the user can confirm the delete or cancel it, as shown below.
8. After selecting 'Yes' or 'No' on the 'Delete concept?' page, the user is returned to the 'Childless concepts' page (UED1).

**'Delete concept' page UED**
![5 - Childess concepts 5 - Delete concept](https://user-images.githubusercontent.com/66372153/109335172-990b2900-7859-11eb-88c1-6f3a8ebab20d.png)

**UED4 - the concept's 'Category' page**
![5 - Childless concepts 3 - V2 - Category link followed](https://user-images.githubusercontent.com/66372153/111659389-185e9d80-8805-11eb-8b93-00699e912439.png)

**Business Rules for UED4**
1. Clicking on the 'Back' link takes the user back to the 'View details' page for the childless concept.
2. The 'Child categories' field will display a link to any child categories, or will display 'None' if there are no child categories.
3. The 'Concepts' field for the category will display a numerical value of the number of concepts belonging to that category.  
4. A list of the category's concepts will be shown beneath the category details.
5. The list of concepts will be paginated and show 5 per page.
6. The category details will remain fixed at the top of the page when the user pages through the list of concepts.     
7. Clicking on 'Edit Category' takes the user to that category's 'Edit' page [see UED3 in ticket #699.  
8. Clicking on a link in the 'Parent' field takes the user to the 'View details' page for the relevant 'Category'.
9. Clicking on the 'View details' link for any of the concepts on this page takes the user to the page shown in UED2.
10. Clicking on the 'Edit' link for any of the concepts on this page takes the user to the Edit page for that concept. 
11. In the 'Category' row for each concept, there should be links to 'View details' and 'Edit' for that category. NB - this is not shown on the UED.
12. There UED is also incorrect in showing a 'View details' link in the 'Data items' row for each of the concepts- there should not be a link to 'View details' in the 'Data items' row for each of the concepts on this page.

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Ticket tested and everything good. Ready to go to UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
