### ISSUE TITLE
Admin Area: redesign 'All data items' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#701]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'All data items' pages to be clear and easy to use
So that I can manage data items effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'All data items' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'All data items' link on the Admin landing page
Then I am taken to the 'All data items' page as shown in UED1

**Scenario 2 - admin user clicks 'View details' link for a data item**
Given I log in to Find & Explore as an admin user
And I am on the 'All data items' page
When I click on the 'View details' link
Then the page I see is as shown in UED2

**UED1 - 'All data items' page**
![7 - All data items 1 - Landing page](https://user-images.githubusercontent.com/66372153/110148786-2c51da80-7dd5-11eb-9129-186fadf43fb8.png)

**Business Rules for UED1**
1. All data items will be listed here.
2. Pagination will be the same as currently applied, with 20 data items displayed on a page.
2. Clicking 'Home' on the breadcrumb will return the user to the Admin landing page.

**UED2 - 'View details' page**
![7 - All data items 2 - View detail](https://user-images.githubusercontent.com/66372153/110149190-a5513200-7dd5-11eb-96f3-322150b3f485.png)

**Business Rules for UED2**
1. Clicking the 'Back' link takes the user back to the 'All data items' page.
2. Clicking the link in the 'Concept' field takes the user to the details page for that concept (an existing page so not described in this story) 
3. If the data item has not been assigned to a concept, the 'Concept' field will state 'No concept'.
4. Clicking the link in the 'Datasets' field takes the user to the details page for that dataset (an existing page so not described in this story) 
5. Data items will always belong to a dataset, so the 'Datasets' field will always display a link to a dataset.

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested and everything good. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
