### ISSUE TITLE
Admin Area: redesign 'All datasets' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#702]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'All datasets' pages to be clear and easy to use
So that I can manage datasets effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'All datasets' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'All datasets' link on the Admin landing page
Then I am taken to the 'All datasets' page as shown in UED1

**Scenario 2 - admin user clicks 'View details' link for a dataset**
Given I log in to Find & Explore as an admin user
And I am on the 'All datasets' page
When I click on the 'View details' link
Then the page I see is as shown in UED2

**Scenario 3 - admin user clicks 'Edit' link for a dataset**
Given I log in to Find & Explore as an admin user
And I am on the 'All datasets' page
When I click on the 'Edit' link
Then the page I see is as shown in UED3

**Scenario 4 - admin user clicks 'Create a new dataset' link on 'All datasets' page**
Given I log in to Find & Explore as an admin user
And I am on the 'All datasets' page
When I click on the 'Create a new dataset' link
Then I am taken to the 'Create datasets' page 

**UED1 - 'All datasets' page**
![8 - All datasets 1 - Landing page](https://user-images.githubusercontent.com/66372153/110354814-78e52200-8030-11eb-953b-6b3ee1594895.png)

**Business Rules for UED1**
1. All datasets will be listed here.
2. Pagination will be the same as currently applied, with 20 data items displayed on a page.
3. Clicking 'Home' on the breadcrumb will return the user to the Admin landing page.
4. Clicking the 'Create a new dataset' link will take the user to the existing 'Create datasets' page (this is existing functionality). 

**UED2 - 'View details' page**
![8 - All datasets 2 - View dataset link followed](https://user-images.githubusercontent.com/66372153/110355102-c6fa2580-8030-11eb-9fa5-8587d98d7988.png)

**Business Rules for UED2**
1. The dataset details will be displayed at the top of the page, as shown in UED2. 
2. Clicking 'Back' at the top of the page will take the user back to the 'All datasets' page (UED1).
2. Clicking the 'Edit dataset' link will take the user to the edit page for that dataset, as shown in UED3. 
3. The dataset's data items will be displayed underneath the dataset details, in a paginated table.
4. Pagination rules for the data items will be the same as for the 'Data items' admin page, see ticket #701 UED1.
5. Clicking the 'View details' link for a data item will display the details page for that data item, as shown on ticket #701 UED2.   

**UED3 - 'Edit' page**
![8 - All datasets 3 - Edit link followed](https://user-images.githubusercontent.com/66372153/110355300-fb6de180-8030-11eb-8e47-063c4e66ed78.png)

**Business Rules for UED3**
1. The user can edit any of the fields shown in UED3.
2. Changes to the fields will be applied when the user clicks the 'Update dataset' button.
3. Clicking the 'Cancel' button will return the user to the 'All datasets' page without applying any changes to the fields.
4. Clicking the 'Back' link will return the user to the 'All datasets' page without applying any changes to the fields.
5. Clicking the 'View dataset' link will take the user to the details page for that dataset, as shown on UED2.
6. Clicking the 'Delete dataset' button will take the user to a confirm delete page, as shown in UED4.
7. The user can select either 'Yes, delete <dataset name>' or 'No, do not delete <dataset name>.
8. If the user selects 'Yes, delete <dataset name>' and clicks the confirm button, the dataset and all of its data items will be destroyed, and the user will be returned to the 'All datasets' page, where that dataset will have been removed from the list of datasets.
9. If the user selects 'No, do not delete <dataset  name>', then the dataset and its data items will not be destroyed, and the user will be returned to the 'All datasets' page, and that dataset will still appear in the list of datasets. 

**UED4 - 'Confirm delete' page**
![8 - All datasets 4 - Delete](https://user-images.githubusercontent.com/66372153/110676978-8505e680-81cc-11eb-943c-c5ebebc20d8c.png)

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
@cacquani - I've tested this and generally it's good but there is a fairly important issue: 
When you select the CTA to delete the dataset, then select 'No, do not delete <dataset name>', it deletes the dataset.
Selecting 'Yes, delete <dataset name>' also deletes the dataset, as it should.

**Comment by dgamblin3008** [comment]
Tested, 'delete dataset' issue fixed. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
