### ISSUE TITLE
Admin Area: redesign 'Recent uploads' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#703]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Recent uploads' page to be clear and easy to use
So that I can administer the uploads effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Recent uploads' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Recent uploads' link on the Admin landing page
Then I am taken to the pages described in the Acceptance Criteria below

**Business Rules** 
1. The 'Recent uploads' page is the same page as is currently accessed by clicking 'Manage Uploads and Downloads' in the production environment.
2.  There are changes to the text as follows: the page header should be renamed from 'Manage Uploaded files' to 'Recent uploads'; the title of the table 'Information Architecture Uploads' should be changed to 'Categories and Concepts Uploads'.
3. There should also be a breadcrumb added to the top of the page to allow the user to navigate back to the home page, that says 'Home > Recent uploads'.

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
