### ISSUE TITLE
Admin Area: redesign 'Import categories and concepts backup file' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#704]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Import categories and concepts backup file' pages to be clear and easy to use
So that I can administer Find & Explore effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Import categories and concepts backup file' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Import categories and concepts backup file' link on the Admin landing page
Then I am taken to the 'Import categories and concepts backup file' page as shown in UED1

**UEDs**

**UED - 'Import categories and concepts backup file' page**
![3 - Import 1 - Landing page](https://user-images.githubusercontent.com/66372153/110357725-818b2780-8033-11eb-809a-b790766036e1.png)

**Business Rules**
1. The 'categories and concepts backup file' is simply the new name for the current Information Architecture file, so the 'Import categories and concepts backup file' page replaces the page currently accessed by clicking 'Import Information Architecture File' and has the same functionality but with some minor changes as described in the following points 2 to 5.
2. The title of the page should be changed from 'Reset Categories and Concepts from an Excel Information Architecture File' to 'Import categories and concepts backup file'.
3. The text 'Categories file in Excel format' should be changed to 'Categories and concepts backup file to import'.
4. The text on the green 'Upload' button is changed to 'Continue' but its functionality is unchanged.
5. A breadcrumb is added to the top of the page, and clicking 'Home' takes the user back to the Admin landing page.

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested, no issues. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
