### ISSUE TITLE
Admin Area: redesign 'Create categories and concepts backup file' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#705]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Create categories and concepts backup file' pages to be clear and easy to use
So that I can administer Find & Explore effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Create categories and concepts backup file' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Create categories and concepts backup file' link on the Admin landing page
Then I am taken to the 'Create categories and concepts backup file' page as shown in UED1

**UED1 - 'Create categories and concepts backup file' page**
![4 - Create 1 - Landing page](https://user-images.githubusercontent.com/66372153/110452376-05d5bd00-80bd-11eb-8799-274bdf067469.png)

**Business Rules**
1. The 'categories and concepts backup file' is simply the new name for the current Information Architecture file, so the 'Create categories and concepts backup file' page replaces the page currently accessed by clicking 'Export Information Architecture File' and has the same functionality but with some minor changes described in the following points 2 to 6.
2. There is a breadcrumb at the top of the page, and clicking 'Home' returns the user to the admin home page.
3. All other text on the page should be changed to that shown on UED1.
4. After clicking 'Continue', the 'spinner' page to be displayed while the file is being created is as shown at UED2. 
5. When the file is successfully created, a new page is displayed as shown at UED3.
6. On UED3, clicking 'Continue to "NPD Admin" home' takes the user to the home page. 

**UED2**
![4 - Create 2 - Generating spinner](https://user-images.githubusercontent.com/66372153/110466091-2c9bef80-80cd-11eb-8272-a8e3b3bae566.png)

**UED3**
![4 - Create 3 - Generating completed](https://user-images.githubusercontent.com/66372153/110466120-39204800-80cd-11eb-9e64-c63ca9c89c02.png)

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested and everything good. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
