### ISSUE TITLE
Admin Area: redesign 'Manage admin users' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#706]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Manage admin users' pages to be clear and easy to use
So that I can administer Find & Explore effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Manage admin users' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Manage admin users' link on the Admin landing page
Then I am taken to the 'Manage admin users' page as shown at UED1

**Scenario 2 - admin user clicks a 'View details' link on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I click on the 'View details' link for an admin user
Then I am taken to the page shown at UED2

**Scenario 3 - admin user clicks an 'Edit' link on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I click on the 'Edit' link for an admin user
Then I am taken to the page shown at UED3

**Scenario 4 - admin user deactivates a user account on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I click on the 'Deactivate' link for an active admin user
Then I am asked to confirm the deactivation, as shown at UED4
If I select 'Yes, deactivate<username>' and click 'Confirm'
Then that user's admin account is deactivated
And the entry for that user will be moved from the 'Active admin users' section to the 'Inactive admin users' section
And a link will be shown to 'Reactivate' that user account, as shown in UED1

**Scenario 5 - admin user clicks 'Deactivate' for a user account on 'Manage admin users' page but cancels the deactivation**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I click on the 'Deactivate' link for an active admin user
Then I am asked to confirm the deactivation, as shown at UED4
If I select 'No, do not deactivate<username>' and click 'Confirm'
Then that user's admin account is not deactivated
And I am returned to the 'Manage admin users' page, as shown in UED1

**Scenario 6 - admin user clicks a 'Reactivate' link on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I click on the 'Reactivate' link for an inactive admin user
Then that user's admin account is reactivated
And the entry for that user will be moved from the 'Inactive admin users' section to the 'Active admin users' section
And a link will be shown to 'Deactivate' that user account, as shown in UED1   

**Scenario 7 - admin user clicks the 'Create a new admin user' link on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I click on the 'Create a new admin user'
Then I am taken to the existing 'New admin user' page [functionality is unchanged] 

**Scenario 8 - admin user searches for a valid admin user account on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I fill in the search filed with part or all of a valid admin user name
And I hit keyboard return
Then I am shown the entries for all of the admin users matching the search criteria
And the number of search results is shown above the list of users

**Scenario 9 - admin user searches for an invalid admin user account on 'Manage admin users' page**
Given I log in to Find & Explore as an admin user
And I am on the 'Manage admin users' page
When I fill in the search filed with part or all of an invalid admin user name
And I hit keyboard return
Then there are no admin user account details shown
And 'No result found' is displayed

**UED1**
![1 - Admin users 1 - List of admin users](https://user-images.githubusercontent.com/66372153/110465861-df1f8280-80cc-11eb-84f3-76e132238361.png)

**Business Rules for UED1**
1. All active and deactivated admin user accounts will be listed.
2. Active user accounts will be shown in the 'Active user accounts' section and deactivated user accounts in the 'Inactive admin users' section.

**UED2**
![1 - Admin users 3 - View admin user detail](https://user-images.githubusercontent.com/66372153/110779725-c7c2cf80-825b-11eb-89ea-c81c5429d1c3.png)

**Business Rules for UED2**
1. Clicking 'Back' returns the user to the 'Manage admin users' page.
2. Clicking 'Edit admin user' takes the user to the edit page as shown at UED3.
3. 'Latest sign in' details are for the most recent sign in.
4. 'Previous sign in' details are for the sign in before the most recent sign in.

**UED3**
![1 - Admin users 2 - Edit admin user](https://user-images.githubusercontent.com/66372153/110779755-d5785500-825b-11eb-8292-505499c8cf52.png)

**Business Rules for UED3**
1. Clicking 'Back' returns the user to the 'Manage admin users' page.
2. The password rules are as shown in the UED (unchanged from existing functionality).
3. All fields must be completed before the user clicks 'Update'.
4. If all fields are completed with valid entries and the user clicks 'Update', the details will be updated and the user will be informed that the account has been successfully updated.
5. If a user clicks 'Update' and any of the fields are incomplete or invalid, an error message will displayed.
6. The user may click 'Cancel' at any time and be returned to the 'Manage admin users' page, any changes made on the edit page will not be applied. 

**UED4**
![1 - Admin users 4 - Deactivate user](https://user-images.githubusercontent.com/66372153/110465982-05452280-80cd-11eb-8b83-2c7a6df5ee33.png)

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested and everything good. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
