### ISSUE TITLE
Admin Area: redesign 'Search index refresh' pages

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#707]
A UX designer has resigned the F&E admin tool landing page and a number of the admin functions that link from the landing page. These changes are purely to improve usability and will not affect the actual admin functionality.

**USER STORY**
As a Find & Explore admin user
I want the 'Search index refresh' pages to be clear and easy to use
So that I can administer Find & Explore effectively

**ACCEPTANCE CRITERIA**

**Scenario 1 - admin user clicks 'Search index refresh' link on Admin user landing page**
Given I log in to Find & Explore as an admin user
When I click on the 'Search index refresh' link on the Admin landing page
Then I am taken to the 'Start search index refresh' page as shown in UED1

**UED1 - 'Search index refresh' page**
![2 - Start search index refresh 1 - Landing](https://user-images.githubusercontent.com/66372153/110463949-70d9c080-80ca-11eb-88af-1375b8cfdbb4.png)

**Business Rules**
1. The 'Start search index refresh' page is the same page as is currently accessed by clicking 'Refresh search index' in the production environment.
2. The text of the page should be changed to match that shown on UED1.
3. The button that currently says 'Start refresh' should be renamed 'Continue'.
4. A 'Cancel' button should be added that takes the user back to the Admin home page without doing an index refresh.  
5. After a successful search index refresh, a page should be displayed as shown at UED2. Clicking 'Continue to "NPD Admin" home' closes this page and returns the user to the Admin home page. 

**UED2 - 'Search index refresh successful' page**
![2 - Start search index refresh 2 - Refresh completed](https://user-images.githubusercontent.com/66372153/110464376-f8273400-80ca-11eb-9dae-b1ed0a291ad0.png)

**Comment by dgamblin3008** [comment]
Assigning ticket to @GMcGill-DfE for approval.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested and everything good. Ready for UAT.

**Comment by dgamblin3008** [comment]
Released to production and tested. Closing ticket.
