### ISSUE TITLE
User facing pages – Google Analytics

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#71]
### Add Google Analytics to the user facing part of the website

**As a** project manager
**I want** analytics data
**in order to** know how users navigate the site and improve their experience

### Scenarios

**Given** a non admin user
**When** the user navigates the site
**Then** their actions will be collected and aggregated through Google Analytics

**Comment by petelonsdale** [comment]
I've sent an email to James Heath asking if he can give some guidance on how we get this service added. I've CC'd Jon, Ryan and Rich into the message in case he doesn't reply while I still have access to my edu email account.
