### ISSUE TITLE
Change text on 'My List' page

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#737]
**INFO**
1. An NPD data sharing caseworker (Martin Johnson) reported that an applicant tried to submit the output from their 'My List' with their data sharing application. On being informed they had to submit the Data Tables instead, they pointed out that there wasn't anything on the My List page that informed them not to use their My List as part of their data sharing application, and that they'd spent a full day compiling their My List.
2. To avoid this happening, the wording on the My List page, under the 'My List' header, that currently states 'You can export this list of data items into a .xlsx or .ods file', **should be changed to** 'As you explore information about the type of data held in the NPD, you can create a ‘My List’ of data items that are of interest to you. You can export this list into a .xlsx or .ods file, which may help when completing the NPD Data Tables that should be submitted when applying to DfE for NPD data.’

**USER STORY**
As an data sharing applicant 
I want to be informed that I should not submit 'My List' with my application for data
So that I don't submit the wrong form

**ACCEPTANCE CRITERIA**
1. The text on the My List page is amended, see INFO 2 above for details.

**Comment by dgamblin3008** [comment]
Suggested wording sent to Gwen McGill on 7/5/2021.

**Comment by dgamblin3008** [comment]
Assigning to @GMcGill-DfE for approval. 
Gwen - the text that I agreed with you by email included 'The list will be saved until you remove all of the data items or clear your cookies' - however, this text is already in the blue box next to the new text, so doesn't need to be added.

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Checked on staging, looks fine. Next stage is UAT before deciding on a release to live data.

**Comment by dgamblin3008** [comment]
UAT completed, moving to 'Ready for Release'.

**Comment by dgamblin3008** [comment]
Released to live on 22/06/2021.

**Comment by dgamblin3008** [comment]
Tested on live and everything good. Assigning to @GMcGill-DfE for approval to close the ticket.

**Comment by GMcGill-DfE** [comment]
Approved
