### ISSUE TITLE
Change column header name in 'My List' output file

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#739]
**INFO**
1. If the 'My List' output file is to be used to specify the data items required as part of the data sharing application process, there must be a way of specifying the years required for each data item.
2. When output to an xlsx or ods file, the final column on each worksheet is headed 'Notes'. Changing this wording to 'Years required' will allow the user to specify the years required for each data item.

**USER STORY**
As a requestor of DfE data
I want to specify the years required for each data item
So that my application includes the data items I require 

**ACCEPTANCE CRITERIA**
Given I have put together a 'My List' of the data items I require
When I export this list to a .xlsx or .ods file
Then the title of the final column for each tab (column F) is 'Years required'

**Comment by GMcGill-DfE** [comment]
Approved

**Comment by dgamblin3008** [comment]
Tested on staging with .xlsx and .ods files, looks fine. Next stage is UAT before deciding on a release to live data.

**Comment by dgamblin3008** [comment]
UAT completed, moving to 'Ready for Release'.

**Comment by dgamblin3008** [comment]
Released to live 22/06/2021.

**Comment by dgamblin3008** [comment]
Tested on live. Assigning to @GMcGill-DfE for approval to close the ticket.

**Comment by GMcGill-DfE** [comment]
Approved
