### ISSUE TITLE
Admin pages: change text on 'Import categories and concepts backup file' page

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#740]
**INFO**
1. When an admin user decides to import a categories and concepts backup file, they should be informed that this will overwrite the existing categories and concepts structure.
2. On the 'Import categories and concepts backup file' page, under the page header the text currently states, 'Categories and concepts backup file to import'; this should be changed to, 'Select a categories and concepts backup file to import. Importing this file will overwrite the existing categories and concepts structure.'.

**USER STORY**
As a F&E admin user
I want to be informed that importing a categories and concepts backup file will overwrite the existing categories and concepts structure
So that I don't erase the existing structure by mistake

**ACCEPTANCE CRITERIA**
Given I am logged into F&E as an admin user
When I click on 'Import categories and concepts backup file'
Then I am informed that importing this file will overwrite the existing categories and concepts structure (see INFO 2 above for wording)

**Comment by dgamblin3008** [comment]
@GMcGill-DfE - on going through my recent notes to make sure I hadn't missed anything, I noticed that you'd asked for this ticket to be added. Assigning to you for approval.

**Comment by dgamblin3008** [comment]
Checked on staging, looks fine. Next step is UAT before deciding on a release date.

**Comment by dgamblin3008** [comment]
Tested on staging, using a file downloaded from live, everything looks fine. This one can only properly be tested on live, so we won't know whether it's worked until it's released to live. For now, next step is UAT before deciding on a release to live date.

**Comment by dgamblin3008** [comment]
UAT completed, moving to 'Ready for Release'

**Comment by dgamblin3008** [comment]
Released to live 22/06/2021.

**Comment by dgamblin3008** [comment]
Tested on live. Assigning to @GMcGill-DfE for approval to close the ticket.

**Comment by GMcGill-DfE** [comment]
Approved
