### ISSUE TITLE
Apply updates to fix 'rubygems' package vulnerabilities

### ISSUE THREAD

**Issue by dgamblin3008** [DFE-Digital/npd-find-and-explore#741]
Two Github 'bots', Depedabot and Snyk, have created three pull requests to fix vulnerabilities in the 'rubygems' dependencies for the files 'gemfile' and 'Gemfile.lock'. The pull requests are #698, #709 and #736.

**Comment by dgamblin3008** [comment]
@cacquani - I'm not sure I can test this. I suppose the confirmation that it's been done is that we won't get any more automated pull requests from Snyk. I'll move to 'Testing' and then to 'Released' and 'Done' with the rest of the tickets.

**Comment by krios82** [comment]
@dgamblin3008 the only way to test this is to test that everything works fine.

Unfortunately, this is not the end of Snyk automated pull requests.

Vulnerabilities are a dynamic thing: people use the libraries, sometimes they find new problems no-one had noticed before, the new problems get thoroughly tested to verify which versions of the library are affected and how to fix them, the report is published in the appropriate databases and Snyk issues a *new* automated pull request to fix the *new* vulnerability that has been just found, so you will definitely get more of these in the future.

As a proof, there are two more that have been opened in the last week, I will double check and merge these too.

**Comment by dgamblin3008** [comment]
Thanks @cacquani . Just one question - is this just an internal issue that applies only to GitHub, or has it been applied to staging and needs to be released to production?

**Comment by krios82** [comment]
@dgamblin3008 this like a Windows update for the app.
It has been applied to staging and will need to be promoted to production, but since this application is low risk it's OK to wait until the rest of the issues are solved.

**Comment by dgamblin3008** [comment]
Released to live on 22/06/2021.
As this is a security update to Ruby on Rails, it can't really be tested.
Assigning to @GMcGill-DfE for approval to close.

**Comment by GMcGill-DfE** [comment]
Approved
