### ISSUE TITLE
Upgrade Webpacker to the current version

### ISSUE THREAD

**Issue by krios82** [DFE-Digital/npd-find-and-explore#92]
Upgrading Webpacker from 3 to 4 breaks the `stylesheet_pack_tag`.

Check why this happens and upgrade Webpacker to the current version

**Comment by spikeheap** [comment]
Ahah! This is a change in behaviour introduced in a minor version upgrade of webpacker :/. Someone raised it in https://github.com/rails/webpacker/issues/1846, and it broke here: https://github.com/rails/webpacker/pull/1625/files.

We need to update `webpacker.yml` with:

```
extract_css: true
```

I'll do that shortly.
